### ISSUE TITLE
example.env when migrating to v7 issues

### ISSUE THREAD

**Issue by derletztename** [FarmBot/Farmbot-Web-App#1019]
First, you should not delete everything below line 64, then you will lose the database settings you need to migrate your database.

Second, what's supposed to go in here?
"username:password" are easy, but whats my "host_name" shall the number stay the same? And what's my database name?
 
`postgres://username:password@host_name:5432/database_name`

And third, it's a little too easy to just tell us you don't support with database migration. The database is the most crucial thing of ones farmbot, once it's ruined, all the data of the plants is lost. Is like fucking up ones precious work with just a tiny update. There wasn't even a warning to consider backing up before updating. And as the previous versions were relatively unstable (at least for me) the temptation to update was pretty big.
So please help me out now as I'm being trapped between the version :(
And by helping me, helping all the others that will follow...

**Comment by derletztename** [comment]
Sorry for my choice of words, I was a little aroused yesterday. The fear of losing my precious database and the worry of not being able to sort this out myself as the instructions are not explicit enough, was a little too much

**Comment by RickCarlino** [comment]
@derletztename You have a few options:

# Option 1: Stay on API v6, Don't Migrate

If you would rather not deal with data migration, you have the option to downgrade. This is the quickest solution.

 1. Pick a [release](https://github.com/FarmBot/Farmbot-Web-App/releases) that worked well for you in the past (v6.6.3 is the latest v7 version).
 2. [Revert to that tag](https://stackoverflow.com/questions/6872223/how-do-i-revert-master-branch-to-a-tag-in-git) using Git.

# Option 2: Upgrade the API, Use Old DB  

1. Set the `DATABASE_URL` to your old database. Your `host` will be your machines _real_ IP address (not `localhost` or `0.0.0.0`). The database name is most likely something like `farmbot_production`, `farmbot_prod` or `farmbot_development`, depending on what your `RAILS_ENV` was set to.
2. You may need to [configure PostgreSQL to allow remote connections](https://blog.bigbinary.com/2016/01/23/configure-postgresql-to-allow-remote-connection.html). Please learn about how to secure a PostgreSQL database if you choose this option. I can't provide PostgreSQL training.

# Option 3: Migrate old DB to Docker with `pg_dump`

 1. [Create a backup using pg_dump](https://www.digitalocean.com/community/tutorials/how-to-backup-postgresql-databases-on-an-ubuntu-vps). The command you want is probably `pg_dump -U postgres -h localhost -p 5432 farmbot_development > my_backup` (or `farmbot_prod` or `farmbot_production`- it depends on your local setup).
 2. Run the command below. You will need to change two things before you can copy/paste:
    * Replace `password123` with whatever your `POSTGRES_PASSWORD` var is set to
    * Replace `farmbot_development` with the real DB name. If `RAILS_ENV` is `production`, use `farmbot_prod`. Otherwise, use `farmbot_development`.

```
sudo docker-compose run web psql -d postgres://postgres:password123@db/farmbot_development < my_backup
```

## Other Notes

Ruby on Rails stores database info (password, username, host, etc) in `Rails.configuration.database_configuration`. You can access it from the Rails console `sudo docker-compose run web rails c` (v7) or via `rails c` (<= v6).

**Comment by derletztename** [comment]
Thank you Rick for this far more detailed answer.
I think the last one is the most sustainable one. And in this new more explicitly explained way I might be able to manage it. There is just a little issue directly in the beginning. When I want to create the backup I get asked for a password. In your notes you have mentioned even that somehow. And while reading [here](https://edgeguides.rubyonrails.org/configuring.html#configuring-a-database) I learned that the database infos can either be stored in the config/database.yml or in ENV['DATABASE_URL']. So I tried setting the passwort in the database.yml which seems to change nothing at all. So you used the ways via ENV['DATABASE_URL']?
And to change data in that I need to use Rails commands? I tried that as well, but man this is another level again.
So concluding, could you maybe please explain if you have used the yml or the ENV['DATABASE_URL'] or both together and how to set the passwort then? Because in the instructions there are different ways for each configuration style

**Comment by derletztename** [comment]
I think I managed to change the password with the database.yml, as following your commands there appears the password several times in the list. But still when trying to make that backup when I get asked for the password, I get an error saying that it's wrong. I think I always have used the development environment not production..

derletztename@permabot_server:~/farmbot-web-app$ rails c
W, [2018-10-24T09:14:34.643560 #3980]  WARN -- Skylight: [SKYLIGHT] [3.0.0] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Loading development environment (Rails 5.2.1)
[1] pry(main)> Rails.configuration.database_configuration
=> {"default"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01"},
 "development"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01",
   "database"=>"farmbot_development"},
 "test"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01",
   "database"=>"farmbot_test"},
 "production"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
:...skipping...
=> {"default"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01"},
 "development"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01",
   "database"=>"farmbot_development"},
 "test"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01",
   "database"=>"farmbot_test"},
 "production"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01",
   "database"=>"farmbot_prod"}}
:...skipping...
=> {"default"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01"},
 "development"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01",
   "database"=>"farmbot_development"},
 "test"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01",
   "database"=>"farmbot_test"},
 "production"=>
  {"adapter"=>"postgresql",
   "encoding"=>"unicode",
   "host"=>"db",
   "pool"=>5,
   "username"=>"postgres",
   "password"=>"permabot01",
   "database"=>"farmbot_prod"}}

**Comment by derletztename** [comment]
I'm really feeling stupid right now.
I deleted the line in the .env file and changed the password in the database.yml and it really has changed if I look with the rails console (rails c), but still I get this error below. Where else could this password been set or what else could be the issue? I mean it clearly looks like being a password issue, but maybe there is something else behind?

```
derletztename@permabot_server:~/farmbot-web-app$ pg_dump -U postgres -h localhost -p 5432 farmbot_development > Paul_backup
Password: 
pg_dump: [archiver (db)] connection to database "farmbot_development" failed: FATAL:  password authentication failed for user "postgres"
FATAL:  password authentication failed for user "postgres"
```

**Comment by RickCarlino** [comment]
@derletztename: Try resetting your PostgreSQL password.

Go in to PostgreSQL:

```
$ sudo -u postgres psql
```

Then list all users:
```
psql (10.5 (Ubuntu 10.5-0ubuntu0.18.04))
Type "help" for help.

postgres=# \du
```

Which will show something like this:

```
                                        List of roles
     Role name      |                         Attributes                         | Member of 
--------------------+------------------------------------------------------------+-----------
 postgres           | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 rick               | Superuser                                                  | {}
```

You can change your password with:

```
postgres=#  ALTER USER your_username_here with password 'whatever';
```

Please refer to StackOverflow and the official documentation for more information. Many of these operations are specific to Docker, PostgreSQL and Rails.

**Comment by derletztename** [comment]
That's had done the trick for me, now the passwort is set :)
`\password postgres`

**Comment by RickCarlino** [comment]
@derletztename The `backup` file is just SQL. Look for your points in there, you should see them if you backed up the correct database.

**Comment by derletztename** [comment]
Yeah, everything seems to be in there, it's several pages long and I recognised my sequences and stuff.

Could you please tell me how to get the infos out of there into the new database?

Just migrate again with this Snippet?:
`sudo docker-compose run web psql -d postgres://postgres:password123@db/farmbot_development < my_backup`

**Comment by derletztename** [comment]
So I tried to migrate it but I received a lot of errors. Here is a extract of the 3 blocks with errors.
Could you please help me integrate the old database in the new one? I have no idea what's wrong and I have spend some long hours with an friend with a lot coding experience who couldn't figure it out as well :(

```
ALTER SEQUENCE
ERROR:  relation "edge_nodes" already exists
ERROR:  role "derletztename" does not exist
ERROR:  relation "edge_nodes_id_seq" already exists
ERROR:  role "derletztename" does not exist
ALTER SEQUENCE
ERROR:  relation "farm_events" already exists
ERROR:  role "derletztename" does not exist
ERROR:  relation "farm_events_id_seq" already exists
ERROR:  role "derletztename" does not exist
.
.
.
ALTER TABLE
ERROR:  duplicate key value violates unique constraint "ar_internal_metadata_pkey"
DETAIL:  Key (key)=(environment) already exists.
CONTEXT:  COPY ar_internal_metadata, line 1
COPY 0
ERROR:  duplicate key value violates unique constraint "devices_pkey"
DETAIL:  Key (id)=(1) already exists.
CONTEXT:  COPY devices, line 1
COPY 0
.
.
.
ERROR:  multiple primary keys for table "ar_internal_metadata" are not allowed
ERROR:  multiple primary keys for table "delayed_jobs" are not allowed
ERROR:  multiple primary keys for table "devices" are not allowed
ERROR:  multiple primary keys for table "diagnostic_dumps" are not allowed
ERROR:  multiple primary keys for table "edge_nodes" are not allowed
```

**Comment by derletztename** [comment]
Also after each reboot the password in Rails.configuration.database_configuration is `nil`, maybe there is also something wrong with rights management settings?
I am so lost at this point, I would even pay you to SSH onto my server and sort things out in a few minutes
