### ISSUE TITLE
Cannot update Web-App anymore

### ISSUE THREAD

**Issue by derletztename** [FarmBot/Farmbot-Web-App#1099]
# Expected Behavior
after 

> rails api:update

 the Web-App should update

# Actual Behavior
![update_notworking](https://user-images.githubusercontent.com/7712645/51678493-d64ac000-1fdc-11e9-85e5-ea76b1fcc102.jpg)

**Comment by RickCarlino** [comment]
@derletztename Can you try this in the meantime while I work on a fix?

```
git pull https://github.com/FarmBot/Farmbot-Web-App.git master
sudo docker-compose run web bundle install
sudo docker-compose run webpack npm install
sudo docker-compose run web rails db:migrate
```

**Comment by derletztename** [comment]
I have no idea what exactly happend there, but it seems to be updated now and everything is just working fine :)

**Comment by derletztename** [comment]
Actually it does seem I have not the newest version on the server. When I compare to https://forum.farmbot.org/t/december-19-2018-software-update/4352
it still looks like the old version. If I look into version (top right corner) it says none.
How can I check if I have the new version?

**Comment by derletztename** [comment]
I don't have the feeling the update worked. Even after logging out the old screen appears:
![farmbot](https://user-images.githubusercontent.com/7712645/51700196-d2d02c80-200e-11e9-8211-b27a75543a3b.PNG)

**Comment by derletztename** [comment]
git log -1
> paul@permabotserver:~$ cd Farmbot-Web-App
> paul@permabotserver:~/Farmbot-Web-App$ git log -1
> commit dce91cdcc336c0502edab330090c8eaae7d8bd85 (HEAD -> master)
> Merge: 436a3a2 2633d17
> Author: Rick Carlino <RickCarlino@users.noreply.github.com>
> Date:   Mon Jan 7 14:49:17 2019 -0600
> 
>     Merge pull request #1078 from FarmBot/staging
>     
>     v7.1.1 - Happy Hibiscus
> paul@permabotserver:~/Farmbot-Web-App$
>

**Comment by RickCarlino** [comment]
@derletztename I am suspicious you have a server process running in the background. Can you try this?:

```
sudo docker-compose down
```
Then
```
sudo docker-compose up
```

**Comment by derletztename** [comment]
Ok this is wierd. It looks like there were about 13 web apps running?
![img_20190124_212105](https://user-images.githubusercontent.com/7712645/51706888-12534480-2020-11e9-893e-c2855a68c27e.jpg)
When I want to shutdown the server, do I kill it with ctrl+c and that's it?
Or do I have to type docker-compose down afterwards as well?

**Comment by derletztename** [comment]
But after killing all those web app versions and starting a new one, it still was the old log in screen. So I have to close it again and update again? Can I update the regular way now, as you closed the issue?

**Comment by RickCarlino** [comment]
@derletztename Can you run `sudo docker-compose down` and then try accessing the web app from a browser? I think there still might be a process running somewhere, possibly a very old version of the app.

Is the page still accessible after running `sudo docker-compose down`?

**Comment by RickCarlino** [comment]
@derletztename What is your `RAILS_ENV` set to? If it's `production`, you might need to re-build the web app assets.

Try:

```
sudo docker-compose run webpack npm run build
```

**Comment by derletztename** [comment]
yeah, it's production. So I tried what you suggested and got an error

![img_20190125_202957 1280x606](https://user-images.githubusercontent.com/7712645/51768299-36765a80-20e0-11e9-980e-e0887a5fc628.jpg)

**Comment by RickCarlino** [comment]
Whoops- that's an easy fix. I forgot that the `npm run build` task actually runs in the `web` container rather than the `webpack` container (it calls `bundler` which does not exist in the `webpack` container).

 Please try:

```
sudo docker-compose run webpack npm run build
```

instead.

**Comment by derletztename** [comment]
You mean

> sudo docker-compose run web npm run build

?

**Comment by RickCarlino** [comment]
Correct. I've updated the original message. Please let me know if that fixed the issue.

**Comment by derletztename** [comment]
Started good, but then failed badly :(

![img_20190126_195734 976x1280](https://user-images.githubusercontent.com/7712645/51791614-393b8300-21a6-11e9-9d20-e5155d570802.jpg)

**Comment by RickCarlino** [comment]
I suspect there's an old version of `node-sass` in your `node_modules` directory.

Try:

```
sudo docker-compose run web npm rebuild node-sass
sudo docker-compose run web npm install
sudo docker-compose run web npm run build
```

**Comment by RickCarlino** [comment]
@derletztename It looks like this is a configuration or dependency issue with Webpack on our side. I will investigate the matter on Monday.

**Comment by derletztename** [comment]
Would you like to have a quick skype call (or hangouts or discord) to sort things out more quickly on monday maybe? You could even have access to the server. I guess this would save so much time :D

**Comment by RickCarlino** [comment]
@derletztename Still working on a fix for the issue you noted, I will keep you posted. This is related to some things in the build system, which have been long overdue for some updates.

**Comment by derletztename** [comment]
Okay, doesn't matter atm anyways. Someone stole the power cables out of my farmbot. I don't know what's going on in some peoples mind...

**Comment by RickCarlino** [comment]
@derletztename I'm sorry to hear that! I will keep you posted on the build system status in the meantime.

**Comment by derletztename** [comment]
I don't know much about Github yet, shouldn't we reopen this ticket for the workflow and tracking and stuff like that? Because of this update error you are making changes in the build system... aren't you?

**Comment by RickCarlino** [comment]
@derletztename I have already made a note of this on our internal tracker (where it _is_ an open item) and am able to keep track of the problem elsewhere. If you are curious about what I am working on, feel free to look at [this branch](https://github.com/RickCarlino/farmbot-web-app/tree/parcel)

 * I have isolated the cause.
 * As you read this message, I am actively working on a fix.

**Comment by RickCarlino** [comment]
@derletztename We tried that in the past but found that it was harder to keep track of issues, particularly issues that span across multiple git repos. These days we keep things centralized in an internal Trello board. That might change in the future, but for now, "open" and "closed" do not necessarily mean that we are/are not working on something.

A bit of background on the status of the fix: The breakage happened because of the frontend build system. Rather than try to patch the problem, I've decided to replace the old system with a new one, as this is not the first breakage of its kind. It is going to take a few more days to fix, I think.

**Comment by HamishWHC** [comment]
How's that fix coming along? I'm installing from scratch and getting the same errors from running 'sudo docker-compose run web npm run build'.

**Comment by RickCarlino** [comment]
@HamishWHC @derletztename Still a work in progress. It is stable now, at least. I need to [merge this pull request](https://github.com/FarmBot/Farmbot-Web-App/pull/1103) plus some minor cleanup, then a round of QA, then a final deploy.
