### ISSUE TITLE
Allow keyboard keys to fire manual control arrow buttons

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/farmbot-web-app#111]
@sweddle (Shane) has done some cool open-source work with controlling robots via webrtc. He has already developed the javascript required for this function and he can help us apply it to the FarmBot web app! Welcome to the project Shane!

**Comment by roryaronson** [comment]
I'm gonna close this for now. This may be a nice-to-have in the future, but there are more important things for now.

**Comment by awnp** [comment]
hello
any progress about farmbot on PHP ?
I'm studiying grblweb which is on php, still far to translate farmbot to php
