### ISSUE TITLE
rake assets:precompile error

### ISSUE THREAD

**Issue by nicmel** [FarmBot/Farmbot-Web-App#1136]
# Expected Behavior

compilation OK

# Actual Behavior

compilation error at 
docker-compose run web rake assets:precompile

-> when running no webpage joingable

```
🚨  /farmbot/node_modules/i18next/dist/es/defaults.js:1:9: Export 'get' is not defined (1:9)
> 1 | export { get };
    |         ^
  2 | function get() {
  3 |   return {
  4 |     debug: false,
rake aborted!
Command failed with status (1): [node_modules/parcel-bundler/bin/cli.js bui...]
/farmbot/lib/tasks/api.rake:62:in `parcel'
/farmbot/lib/tasks/api.rake:77:in `block (2 levels) in <top (required)>'
/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile => api:parcel_compile
(See full trace by running task with --trace)

```

# Steps to Reproduce

On a fresh new ubuntu server 18.10
following the master procedure:
I get some warnings with :docker-compose run web npm install

```
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN ts-jest@23.10.5 requires a peer of jest@>=22 <24 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```
but I don't know if it's related, and after that I get the error with docker-compose run web rake assets:precompile

# Results of `git log -1`

commit 26e98cb389551098eac27b0722fe388c19595a5a (HEAD -> master, origin/master)
Merge: d59c907 cc00c74
Author: Rick Carlino <RickCarlino@users.noreply.github.com>
Date:   Fri Mar 8 09:21:25 2019 -0600

    Merge pull request #1127 from RickCarlino/nerveshub_hotfix
    
    HOTFIX: Background worker NPE

**Comment by RickCarlino** [comment]
@nicmel Confirmed. I have reproduced your error locally and am working on a fix.

**Comment by RickCarlino** [comment]
@nicmel The problem is fixed. We need to do some final QA checks before the release goes out though. Thanks for letting us know about this issue.

**Comment by RickCarlino** [comment]
@nicmel QA is done and `v7.2.3` has been released. Please let me know if you have any issues with the latest version.

**Comment by nicmel** [comment]
I'm back, no time until today to look a it.
I'm trying it today
It works.

Thanks
