### ISSUE TITLE
Production password resets don't work

### ISSUE THREAD

**Issue by Br3nda** [FarmBot/Farmbot-Web-App#1152]
# Expected Behavior
I expected the password reset email to include a link that starts with `https://my.farmbot.io` 
# Actual Behavior
the link in the email leads to `http://my.farmbot.io:443`, which the browsers interpret as http (no ssl) on port 443
# Steps to Reproduce
Reset your password on production follow the link in the email.
![image](https://user-images.githubusercontent.com/12266/56099381-2ee88400-5f60-11e9-856f-bbdfede5ece9.png)

**Comment by troymd** [comment]
As a work around I took the link resulting URL that timed out :  "http://my.farmbot.io:443/password_reset/eyJh..." and I fixed it by making it look like this:

"https://my.farmbot.io/password_reset/eyJh...  "

(for not techie types, if your trying to follow my tracks,  the entire rest of the URL is included after the "...", I didn't touch that part)

**Comment by RickCarlino** [comment]
@Br3nda Thanks for finding this. I will work on a fix today :+1: In the mean time, I think the fix that @troymd recommends will fix the issue for anyone affected by this (Thanks!).

**Comment by RickCarlino** [comment]
Fixed on `staging`. There are a few things that still require final QA checks, but it will be deployed to production tomorrow or Wednesday.
