### ISSUE TITLE
Websocket connection error

### ISSUE THREAD

**Issue by tuananh2311** [FarmBot/Farmbot-Web-App#1256]
# Expected Behavior
Able to connect to websocket port 3002
# Actual Behavior
Errors display in browser console, web app cannot connect to Message Broker

`WebSocket connection to 'wss://DOMAIN_NAME:3002/ws' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`

# Steps to Reproduce
Run the webapp and observe the console log

Hi,
I am setting up the web app on AWS, it is running fine except that it cannot connect to the message broker. Could you please help to point out where I did wrong?

THanks

![Screen Shot 2019-07-02 at 7 48 03 PM](https://user-images.githubusercontent.com/804669/60494544-1851fd80-9d03-11e9-9c43-9e2dd8bd7af5.png)

**Comment by RickCarlino** [comment]
@tuananh2311 It looks like the server is trying to use SSL but it is either not configured, or configured improperly. Does the website use HTTPS? Did you correctly configure the certificate if so?

**Comment by tuananh2311** [comment]
> @tuananh2311 It looks like the server is trying to use SSL but it is either not configured, or configured improperly. Does the website use HTTPS? Did you correctly configure the certificate if so?

I got a free cert from Let's Encrypt following this tutorial. Is there some additional config I need to do for websocket?

https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04

**Comment by tuananh2311** [comment]
My nginx config

```
server {
    listen 80;
    listen [::]:80;

    root /home/ubuntu;
    index index.html index.htm index.nginx-debian.html;
    server_name app.rasatechvn.com;
    
    location / {
        rewrite ^ https://$host$request_uri? permanent;
    }
}

server {
    listen [::]:443 ssl;
    listen 443      ssl;
    server_name     app.rasatechvn.com;
    ssl             on;
    
    ssl_certificate /etc/letsencrypt/live/app.rasatechvn.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/app.rasatechvn.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location /  {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect    off;
        proxy_pass        http://app.rasatechvn.com:3000;
    }
}
```

**Comment by RickCarlino** [comment]
@tuananh2311 Our production servers use Heroku and CloudAMQP, which has a very different SSL configuration than your server.

My guess is that RabbitMQ needs to be configured to handle SSL. To do that, you will need to modify `RmqConfigWriter::TEMPLATE` found [here](https://github.com/FarmBot/Farmbot-Web-App/blob/staging/app/lib/rmq_config_writer.rb#L28-L44). I would guess that RabbitMQ requires some sort of config change to be reverse proxied or use SSL.

I don't have time to help with NGinx-based setups right now, unfortunately. I am happy to answer any questions you have about the app or how we use `docker-compose`. If you find a solution, I would be willing to add it to our documentation to help users in a similar situation. I would also be willing to merge changes to `RmqConfigWriter::TEMPLATE` if you find it is necessary for NGinx-based setups. Please let me know.

**Comment by RickCarlino** [comment]
I just found [this](https://www.rabbitmq.com/web-mqtt.html#tls) in the RabbitMQ documentation. It may be of use to you in this situation.

**Comment by tuananh2311** [comment]
Thanks Rick, will give it a try.

**Comment by RickCarlino** [comment]
This issue has not had activity in the last 5 days. I am going to close the issue since this is out of scope for typical support requests. Members of the community are free to continue the discussion, however.
