### ISSUE TITLE
"1 days old" should be "1 day old"

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1288]
# Expected Behavior
When you add a plant, and its age is 1 day old, it should be written as "1 day old" both in the plants list and in the plant details panel.

# Actual Behavior
It is written as "1 days old".

# Steps to Reproduce
Add a plant to the map and look at its age.

**Comment by RickCarlino** [comment]
A few notes for when we get to this one:

 * We will need to use [i18next's pluralization features](https://www.i18next.com/translation-function/plurals) for this one.
 * We will also need to add updates for users contributing translations of languages with complex pluralization rules.
