### ISSUE TITLE
Points panel

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1314]
An panel in the farm designer for creating/managing points

![Points Panel (1)](https://user-images.githubusercontent.com/5524043/61671587-2b6e4280-ac9d-11e9-8513-62928cf1c48c.jpg)

**Comment by roryaronson** [comment]
Here is an updated nav icon (less like the Controls popout icon) and a new matching empty-state graphic for the points panel. Zipped b/c GH doesn't allow SVG uploads.

[Points Graphics.zip](https://github.com/FarmBot/Farmbot-Web-App/files/3714239/Points.Graphics.zip)

**Comment by roryaronson** [comment]
@gabrielburnworth what do you think about making the `edit point` panel have more or less the same layout as the `create point` panel? On staging I'm seeing a pretty different layout of the fields for the edit panel, and there's also no **NAME** field.

<img width="605" alt="Screen Shot 2019-11-07 at 6 21 58 PM" src="https://user-images.githubusercontent.com/5524043/68444385-8617a580-018b-11ea-91f6-c23e44b0a7b8.png">

Perhaps also the title of the edit point panel should just be "Edit Point", to match the edit panels for the other resources, and not get cutoff so soon with longer point names.

**Comment by gabrielburnworth** [comment]
Continued in #1564.
