### ISSUE TITLE
Read-only mode (account setting)

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1321]
Turning this setting on would be a way for an administrator of a FarmBot (in a school, for example) to prevent other people from changing things around and accidentally messing things up.

**Comment by RickCarlino** [comment]
Initial implementation:

 * Add a `user_interface_read_only`<boolean> flag to `WebAppConfig`
 * Add toggle button to web app settings page
 * Add logic to `edit()` and `delete()` and `create()` action creators.
