### ISSUE TITLE
API: "Selecting `all tools` as a location causes CeleryScript::TypeError"

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1347]
```
Body: "Tool" is not a type of point. Allowed values: ["GenericPointer", "ToolSlot", "Plant"]
```

**Comment by RickCarlino** [comment]
The feature as it is currently implmented behind a feature flag, will probably never work and will require re-implementation after the v8 post-RC launch. Rather than a bug, this is an unimplemented feature that will never be implemented in its current form.
