### ISSUE TITLE
Remove /app

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1410]
We talked about removing the `/app` part from the URL routes a long time ago, but I think it was deemed infeasible because of the way the router worked or the way the app was structured back then. Wondering how do-able it is now for short-and-concise-URL's sake, or if its still not worth it. cc @RickCarlino

**Comment by gabrielburnworth** [comment]
> infeasible because of the way the router worked or the way the app was structured

This is still the case. The router needs `/app` to distinguish between static pages and app pages.
