### ISSUE TITLE
reset password not working

### ISSUE THREAD

**Issue by Br3nda** [FarmBot/Farmbot-Web-App#1424]
# Expected Behavior
To be able to reset my password and log in

# Actual Behavior
I can't reset my password - i get an error "all device users must agree to tos"
but there's no where i can aggree to this TOS, and i can't log in to do so.....

![image](https://user-images.githubusercontent.com/12266/64650841-3a3ecd80-d474-11e9-8989-a77426377f4a.png)

# Steps to Reproduce
Reset password
follow link from email
type password twice
press "reset"

# Results of `git log -1`

Run `git log -1` and paste the results here.

**Comment by RickCarlino** [comment]
Thanks for the heads up @Br3nda. Investigating now.

**Comment by RickCarlino** [comment]
@Br3nda I think I see what's happening. Is this happening with the account listed on your Github profile, or a different email? If it's a different email, please send the email address  to my_first_name at farmbot.io.

Also, how old is this account? Was it created more than a year ago?

**Comment by Br3nda** [comment]
It's more than a year old, yes. I managed yo guess my old password, and accept the terms.

I think the password reset form should let you continue, and only on login ask the user to accept the terms.
