### ISSUE TITLE
Increase variable form width to 100%

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1436]
Since decreasing the width of the Execute command's dropdown, the variable form now gets a little too squished on small screens. I suggest increasing its width from 80% to 100%, OR giving the form a set width in pixels, and containing it in a horizontally scrollable div, in prep for multiple variables.
<img width="267" alt="Screen Shot 2019-09-16 at 12 09 04 PM" src="https://user-images.githubusercontent.com/5524043/64985900-cb4de400-d87a-11e9-8a55-27e6265644a1.png">

**Comment by AscendFB** [comment]
I increased the width to 100%, but it was still really squished on low screen widths as seen below - left picture. So I'd suggest to keep the full width column (100%) on screen widths lower than 1075px (mobile and tablet) and only compact the higher resolution screens. 
![execute_step](https://user-images.githubusercontent.com/23129562/66413970-c4893b80-e9f8-11e9-8f80-2a99afa999fc.png)

**Comment by roryaronson** [comment]
@AscendFB that looks like a good plan to me 👍
