### ISSUE TITLE
Logs page does not render markdown, but ticker does.

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-App#1438]
# Expected Behavior

 * Logs page can render markdown in the same way the ticker does.

# Actual Behavior

 * Logs page does not render markdown

# Steps to Reproduce

 * Create a markdown log.
 * Open the log on the logs page.

This bug was reported by @connorRigby

**Comment by gabrielburnworth** [comment]
This is the intended behavior. The log ticker renders markdown and HTML, while the logs page provides a way to view the raw log messages. This is especially important for FarmBot OS error logs, which may include special characters that don't display correctly with markdown enabled.
