### ISSUE TITLE
Zoom Controls Dont Work on  Firefox

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-App#1459]
# Expected Behavior

Pressing the plus and minus buttons in the designer should zoom in and out.

# Actual Behavior

The zoom buttons do nothing.

# Steps to Reproduce

Log in to the app in Firefox.
Enter the Farm Designer page.
Click the zoom buttons after expanding the right top panel.
Observe the unexpected lack of zooming.

# More Information

First report seen [here](https://forum.farmbot.org/t/zoom-buttons-in-farm-designer/5492)

**Comment by gabrielburnworth** [comment]
The Farm Designer uses the CSS zoom property to zoom the map. Firefox is the only browser that does not support the zoom property.
