### ISSUE TITLE
Improve Percent OK network QoS calculation

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1526]
# Expected Behavior
**Percent OK** should be calculated excluding pending pings such that the percent only goes down if a ping has actually failed.

# Actual Behavior
**Percent OK** drops briefly while a ping is pending, and then goes back up when the pong is received. This results in a metric that looks troubling upon first glance when there actually isn't anything to worry about.
![Network QoS](https://user-images.githubusercontent.com/5524043/67444144-adcc1280-f5bc-11e9-8178-c2d9b6585b2e.gif)

**Comment by RickCarlino** [comment]
We will begin work on this feature on Monday.
