### ISSUE TITLE
Disable jog control when at axis maximum

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1531]
# Expected Behavior
When **STOP AT MAX** is enabled and the bot is at the max location, disable the appropriate jog button.

# Actual Behavior
Jog button is enabled, but bot can't actually go farther in that direction.

# Bonus
When a disabled jog button is clicked, show a pop-up that says why it is disabled. Example: "The bot is at the maximum position and **STOP AT MAX** is enabled" or  "The bot is at the home position and **STOP AT HOME** is enabled"

**Comment by gabrielburnworth** [comment]
This is already implemented and appears to be working correctly. Perhaps this is a configuration issue or an edge case while using specific hardware settings?
