### ISSUE TITLE
Your Ruby version is 2.5.3, but your Gemfile specified ~> 2.6.5

### ISSUE THREAD

**Issue by derletztename** [FarmBot/Farmbot-Web-App#1538]
Hi Guys,

I tried to install the Web-App on a fresh system after a long time following your instructions in ubuntu_example.sh and run into an error.
This:
```
# Install application specific Ruby dependencies
sudo docker-compose run web bundle install
```
leads to:
> Your Ruby version is 2.5.3, but your Gemfile specified ~> 2.6.5

If I check by - ruby --version - I get

> ruby 2.5.1p57....

So I guess a normal ruby update would not help there. Could you please help me get the farmbot running again and finish that installation?

**Comment by gabrielburnworth** [comment]
You may run

```
sudo docker-compose build
```
to upgrade to the specified ruby version.

https://github.com/FarmBot/Farmbot-Web-App/blob/staging/ubuntu_example.sh#L78-L87
