### ISSUE TITLE
Is docker configuration really using .env ?

### ISSUE THREAD

**Issue by PitouGames** [FarmBot/Farmbot-Web-App#1598]
In file `docker-compose.yml`, port used by the  API is fixed to 3000. Shouldn't it be linked to the environment variable define in the file `.env` ?
I think it's the same for RAILS_ENV which is hard coded in docker-compose.yml.

# Expected Behavior
When changing `API_PORT=3000` to `API_PORT=80` and then running `docker-compose up` the app should be available on port 80.
# Actual Behavior
Nothing on port 80 and port 3000 is still used by the app.
# Steps to Reproduce
- Clone and install the project using https://github.com/FarmBot/Farmbot-Web-App/blob/69249dc471ed5c0857d4db2b5d09c2d54085efe3/ubuntu_example.sh
- Run app one time with `API_PORT=3000` in `.env`.
- Change it to 'API_PORT=80' and run `docker-compose up` (wait for parcel). You should have lot of AMQP request error as a bonus.

**Comment by RickCarlino** [comment]
@PitouGames You are correct, and I have a local fix. Please standby for a fix. Thanks for letting us know.
