### ISSUE TITLE
Firefox: Checkboxes are not correctly displayed

### ISSUE THREAD

**Issue by PitouGames** [FarmBot/Farmbot-Web-App#1607]
Happen on my.farm.bot and custom local server. This sequence block isn't the only block affected. I think there are checkboxs elsewhere in the app that have the same issue.
# Expected Behavior
Here is the render in web browser Vivaldi
![vivaldi](https://user-images.githubusercontent.com/22180158/69913733-f7214480-143b-11ea-8417-988c0980f26d.jpg)
# Actual Behavior
Here is the render in web browser Firefox
![firefox](https://user-images.githubusercontent.com/22180158/69913736-07392400-143c-11ea-8f82-cd260ff488c6.jpg)
In Firefox, you can't know if checkboxes are checked or not.

**Comment by RickCarlino** [comment]
@PitouGames I have noticed this one also (I am primarily a  FF user). Thanks for making an issue.
