### ISSUE TITLE
Is the CSP blockage intentional?

### ISSUE THREAD

**Issue by PitouGames** [FarmBot/Farmbot-Web-App#1619]
When browsing the app from the host with 127.0.0.1:3000 or any domain that is different than the parameter `API_HOST` in file `.env`, some public 
resources don't load because of CSP and the app doesn't load at all (grey screen with just a text "Loading..." new since 8.2.4).
![Capture du 2019-12-09 21-54-44](https://user-images.githubusercontent.com/22180158/70472559-92b35480-1acf-11ea-9ae6-d8e53d4fc69f.png)

For our server setup in our school, this thing is a little annoying. Is this done on purpose for security reasons or is it a bug?

**Comment by RickCarlino** [comment]
@PitouGames The application was only designed to work with `API_HOST`. We discourage the use of `127.0.0.1` for different reasons, mostly that some users will set their `API_HOST` to `127.0.0.1` which causes trouble for `docker-compose`, making it unable to find services like Redis, PostgreSQL, etc...
