### ISSUE TITLE
Crop search cosmetic improvements

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1632]
* `text-align: center` the crop label
* Change crop label background to `linear-gradient(transparent, rgba(0,0,0,.5))`
* Add `border-radius: 5px` to the crop tiles
* Remove double-column gutter so vertical and horizontal padding between all crop tiles and the panel edges is consistent
* Add `box-shadow: 0px 4px 7px 2px rgba(0,0,0,0.2)` to crop tiles
* On crop tile hover, change `box-shadow` to `0px 5px 8px 2px rgba(0,0,0,0.25)` and `transform: translateY(-1px)` with `animation: 0.2s ease`

### Before
![Screen Shot 2019-12-19 at 12 30 51 PM](https://user-images.githubusercontent.com/5524043/71207313-7182fe80-225b-11ea-930a-4b789524b45f.png)

### After
![Screen Shot 2019-12-19 at 12 30 32 PM](https://user-images.githubusercontent.com/5524043/71207320-78aa0c80-225b-11ea-97c6-6d31afe08797.png)

**Comment by Al-0** [comment]
I will look into this issue.

**Comment by roryaronson** [comment]
Thanks @Al-0! Let us know if you have any questions about the ticket.

**Comment by roryaronson** [comment]
@Al-0 have you made any progress or hit any roadblocks on this ticket? Do you have any questions that we may be able to help you with?

**Comment by Al-0** [comment]
@roryaronson Hello, so sorry for the radio silence, I've been busy with some other work. While trying to use the script for installing the environment on Ubuntu, I ran into the following issue while creating the PostgreSQL db and I'm not sure how to solve it, do you have any idea of what could be causing this?

<img width="719" alt="Screen Shot 2022-01-08 at 22 45 07" src="https://user-images.githubusercontent.com/55642668/148669849-dceff22e-ea3b-4089-9fa0-582cf8b6ffad.png">

**Comment by RickCarlino** [comment]
@Al-0 Did you set the `POSTGRES_PASSWORD` environment varialbe in the `.env` file?

**Comment by Al-0** [comment]
@roryaronson Yes, I did.
