### ISSUE TITLE
[bug, minor] Device page, no Release Notes

### ISSUE THREAD

**Issue by jsimmonds2** [FarmBot/Farmbot-Web-App#1661]
# Expected Behavior
On **DEVICE** tab/page; After pressing drop down **"Release Notes"** I see some relevant text.
# Actual Behavior
Software couldn't get Release Notes ; See image below
# Steps to Reproduce
Run FBOS v9.0.2 and WebApp (my.farm.bot) VERSION A31C21BB
# Results of `git log -1`
N/A
Run `git log -1` and paste the results here.

![image](https://user-images.githubusercontent.com/1224439/72127408-abab7000-33c3-11ea-9309-e67cb9a8d3e2.png)

**Comment by gabrielburnworth** [comment]
Thanks for pointing this out. I've added release notes for version 9, which should show up now.
