### ISSUE TITLE
Criteria-based Groups

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1664]
The ability to define a group with criteria, which can allow the group members to change dynamically with time. For example: a group consisting of all weed points, that changes based on the weeds detected in the garden.
![Screen Shot 2020-01-15 at 1 01 57 PM](https://user-images.githubusercontent.com/5524043/72471295-3e1e8b80-3797-11ea-98c6-d28174833d54.png)

**Comment by RickCarlino** [comment]
# TODO

(Will be updated as I go)

 - [ ] Ensure Group `has_one :fragment, as: :owner`

**Comment by roryaronson** [comment]
Based on conversation with @RickCarlino and early testing, the current UI for selecting criteria (on staging) guides users towards creating a group that is unlikely to be what they want, and is somewhat confusing. Some examples:

- Creating a box-selection in the map to set X/Y location criteria currently selects plants, as well as points, weeds, and slots. I imagine it is _highly unlikely_ a user would want to include points of all these types in a group, because it is unlikely for the user to want to perform the same operation at locations of different types. It would be better I think to limit groups to containing points of only one type. Perhaps we should add a dropdown near the top for **GROUP TYPE** with the options "Plant", "Weed", and "Point", and reveal the other fields once this first selection has been made. Under the hood this would be setting the Pointer Type criteria. This change would allow us to remove the **PRESETS** and the Point type option in additional criteria as they would be largely duplicates.
- When defining criteria using the more human-readable inputs, the content is duplicated in the Advanced section dropdown in a less human-readable way. Not only does the duplication clutter the UI and not really add value, I think the ability to delete the same thing in multiple places, especially when they are named differently is confusing. For example, Plant Type = Broccoli is represented by OpenFarm_Slug = broccoli in the advanced section. I suggest having no duplication of the content to promote a clean UI and minimize possibility of confusion here.
- Adding any criteria or removing all criteria results in the help text in the **GROUP MEMBERS** area to significantly change length and cause a jarring movement of scroll position. I suggest moving all of that help text into a ❓ tooltip to clean the UI of text the user is only likely to read once or twice while learning the feature, and minimize shocks to the scroll position.
- I think it will be really common for people to want to select plants based on crop type and plant status, and feel like its better to break those out into dedicated criteria sections rather than lumped into the same "Additional criteria" section.
- As mentioned in bullet 1, if the user was forced to choose the group point type up-front, the other options could be conditionally displayed in the advanced section (or not at all) so we would only be showing what is relevant to that point type. For example: plant type obviously does not apply to anything other than plants.
- Right now it seems that zones and groups are quite linked. ie: when you create a group, a zone gets created as well. And if you edit a zone's or group's location inputs, the location inputs in the other get updated. This is very confusing to me. I think we either need to
  - Separate the two resources entirely. A zone could be created/edited/deleted on its own and could be added to a group as a criteria. Location criteria would be removed from the groups edit panel and replaced with a zone selector element. Zones could then be used across groups, and if a zone was updated, that update would get used by all groups using the zone at runtime. However, updating the zone itself wouldn't be updating the group itself. Multiple zones could be added to the group.
  - Abandon zones altogether and only allow location criteria to be created within a group.
- Right now it is confusing and inconsistent that you can create a box-selection to select specific plants, then you hit **CREATE GROUP** to create a group with those specific plants as a manual selection. Then subsequent box-selections (from the group edit panel) work differently: they create location criteria that adds plants (or any point for that matter) based on criteria rather than the manual selection. I think it would make more sense to users if box selections from the group-edit panel added plants as manual additions. A location box could be added after clicking a special button, or if we go zone route 1, that whole function could just be removed from the group-edit panel entirely.
