### ISSUE TITLE
unable sign into hosted web app

### ISSUE THREAD

**Issue by waldmannly** [FarmBot/Farmbot-Web-App#1674]
I am currently hosting the web app and able to access it on my local host in production mode on port 80 (if that matters). I am not sure what the admin credentials are to sign in as I could not find them anywhere in the documentation. 

I tried admin@admin.com with password, admin, password123 (this was in some of the test cases), and the passwords for that I set up in my config files, but none of these combinations worked. 

Could someone provide me with the correct credentials or point me to where the credentials would be stored locally, so I can find them? 

Otherwise, if the credentials I listed were the correct ones, could someone given me some guidance on why they would not be working?  

Thanks for the help.

**Comment by RickCarlino** [comment]
@waldmannly FarmBot does not have any default passwords. What are you trying to do that requires default credentials, given that you are already able to access the server on port 80?

**Comment by waldmannly** [comment]
Once I got the server running I was presented with the login\create account screen. I assumed there was an admin account to login with since I did not set up the email part of the config. 

How am I supposed to login?

**Comment by RickCarlino** [comment]
@waldmannly Login on a local server works the same as the official server- you would register for an account. Since most self-hosters do not use email servers, you will probably want to set `NO_EMAILS=true` if you have not already done so.

Did you have any issues when you attempted to register your account?

**Comment by waldmannly** [comment]
Gotcha. I just needed to create and account and sign in with that (even though the website still popped up with the notification that the email verification link needed to be clicked). I honestly didn't think that would work. Thanks for the help!
