### ISSUE TITLE
Improve grid line labels in farm designer

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1685]
# Expected Behavior
The grid line labels (`100`, `200`, etc) should be legible at all zoom levels

# Actual Behavior
At 0.75 zoom and farther out the labels are too small to easily read.

# Suggested Solution
- [ ] Scale the labels inversely to zoom level so they always stay the same size to the user, despite zoom level
- [x] At zoom level 0.5 and farther out switch from labels every 100mm to every 200mm
- [x] At zoom level 0.2 and farther out only show labels every 500mm
- I think a good size for the text might be where the bounding box rendered on screen is 16 to 18px tall. This might take some tweaking to look good.
- There may be some legibility issues with the labels on the left if when they stretch into the darker brown or even gray areas, which may require tweaking. Ideas: adding a text-shadow, making the font bolder or darker in color.

**Comment by roryaronson** [comment]
@FabioDessi this improvement may be of interest to you :)

**Comment by FabioDessi** [comment]
It was already on my list! I'll work on this Il 7 feb 2020 23:09, Rory Aronson <notifications@github.com> ha scritto:@FabioDessi this improvement may be of interest to you :)

**Comment by roryaronson** [comment]
Just saw your improvements to the sizing on the x-axis labels @FabioDessi, thank you! As I suspected, with the increase in font size, the current _location_ of the labels could use improvement. What do you think about shifting the location of the x-axis labels to the right by 15px and up by 10px, and changing `text-anchor` to `start`?
<img width="525" alt="Screen Shot 2020-02-10 at 10 39 15 AM" src="https://user-images.githubusercontent.com/5524043/74179402-3addba80-4bf2-11ea-96eb-2564bc6b19f9.png">

At farther out zoom levels the location offset may need to be increased to maintain spacing between the numbers and the grid lines and bed border.

**Comment by roryaronson** [comment]
@FabioDessi thanks for the second PR 👍 

Here's my feedback so far: the labels look good with the default map rotation and origin location, but they shift around and feel out of place with different map settings.

Default map rotation and origin:
<img width="412" alt="Screen Shot 2020-03-16 at 4 18 15 PM" src="https://user-images.githubusercontent.com/5524043/76807615-2fa61d80-67a2-11ea-89ad-bfa1b081bc50.png">

Rotated map and different origin:
<img width="450" alt="Screen Shot 2020-03-16 at 4 18 33 PM" src="https://user-images.githubusercontent.com/5524043/76807629-392f8580-67a2-11ea-80cd-1400ffcfd818.png">

Here are the settings I'm referring to (found in the settings panel on the far designer page)
<img width="294" alt="Screen Shot 2020-03-16 at 4 24 09 PM" src="https://user-images.githubusercontent.com/5524043/76807730-93c8e180-67a2-11ea-97bf-5881c3d3136c.png">

Could you send in another PR with adjusted label locations based on map rotation and origin settings?

Also, I'm thinking it would be nice to have labels on all four sides of the map, rather than just the x-min and y-min sides.

Let me know what you think!

**Comment by roryaronson** [comment]
@FabioDessi any progress on this? 😄

**Comment by FabioDessi** [comment]
Hi @roryaronson. I'm back on this issue. I'll keep you updated!
