### ISSUE TITLE
Group Editor is setting `days_ago` to "null" instead of "0" 

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-App#1717]
# Expected Behavior

 * Ability to set / unset `days_ago` in a criteria based group.

# Actual Behavior

 * Error toast `Error: [Object object]`.

# Steps to Reproduce

 * Navigate to groups editor
 * Under "AGE SELECTION", change the drop down to `less than`
 * Change the `days_ago` value
 * Blur out of the input field
 * Observe the error `Error: [Object object]` (which is actually a `{"criteria":{"day":{"days_ago":"Days Ago can't be nil"}}}` response, but the FE can't handle nested objects currently.).

The request params are as follows (I have removed most unrelated fields such as `id`, `created_at`, `name`, etc..):

```
{
  "criteria": {
    "string_eq": {
      "meta.created_by": ["farm-designer"],
      "meta.type": ["weed"],
      "pointer_type": ["Plant"]
    },
    "day": {
      // === Root cause:
      "days_ago": null,
      "op":"<"
    },
    "number_eq": {},
    "number_gt": {
      "y": 200
    },
    "number_lt":{
      "y": 300
    }
  }
}
```

**Comment by gabrielburnworth** [comment]
This appears to be a data migration issue from the `days` to `days_ago` change, where the data in the API when opening the form is
```
day: { days: 1, op: "<" },
```

**Comment by RickCarlino** [comment]
Fixed via:

```
PointGroup.where.not(criteria: nil).map {|x| x.criteria[:day][:days_ago] ||= 0; x }.map(&:save!)
```
