### ISSUE TITLE
Farm Designer link in mobile nav should take users to the map, not the plant inventory

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1729]

**Comment by Bioinformatics-Surgeon** [comment]
I would like to take a stab at this issue. Shall I just hop in or is there some house keeping that is needed before I begin?

**Comment by roryaronson** [comment]
@Bioinformatics-Surgeon because this issue has not been assigned to anyone else and is not already `In Progress` on our [Project Board](https://github.com/orgs/FarmBot/projects/8), you can go ahead and hop right in. Thanks!

**Comment by roryaronson** [comment]
@Bioinformatics-Surgeon any progress on this one? If you need assistance or have any questions, we'd be happy to help.

**Comment by roryaronson** [comment]
With the consolidation of pages into farm designer panels, this is no longer relevant.
