### ISSUE TITLE
Homing and Calibration buttons disabled when online

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/Farmbot-Web-App#1734]
Hello everyone,

looks like the 'disable' mechanism on the homing and calibration buttons is flipped.
When the device is online, the buttons are grayed out, when its offline they are clickable.

@RickCarlino or @gabrielburnworth Would be fine if you could take a look into that as this might be confusing for end users 🙂 

Code line example: https://github.com/FarmBot/Farmbot-Web-App/commit/b1c2b36a37432deffef4a28c0e2490481deabdd7#diff-9a45f442af451bec591875b4e4f6dfe6R25

There are additional `botOnline` uses that are also affected, like the `RESET` button in the danger zone.

![image](https://user-images.githubusercontent.com/23129562/76996214-6b331a00-6951-11ea-8b00-c2dd6d0d2214.png)
![image](https://user-images.githubusercontent.com/23129562/76996222-6ec6a100-6951-11ea-9242-a0f48a76ade5.png)

**Comment by RickCarlino** [comment]
Thanks for bringing this to our attention, @AscendFB . We're working on a fix right now and will deploy shortly.
