### ISSUE TITLE
FarmEvent Panel Implements Guard Features Against User Timezone Rather than Device Timezone

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/Farmbot-Web-App#1807]
This is extremely low priority, but I will make a note of it. I discovered this while performing customer support.

# Steps to Reproduce

 * Set device timezone to a negative offset from the browser's timezone. For example, if it is 8 AM local, find a timezone where the current time is 6 AM.
 * Attempt to schedule a Farm Event at 6:15 AM Device time (8:15 AM local). Note that at 8AM local, the time 6:15 AM is in the past. But 6:15AM is in the future in the device's time zone.

# Expected Behavior

 * Ability to schedule a FarmEvent in the near future from a different timezone

# Actual Behavior

 * Web App warns the user that "Events must be scheduled in the future, not the past". It is 8AM in my timezone, but 6AM in the device's timezone.

Again, this is very low priority given other concerns this quarter and the lack of reports from customers.

**Comment by RickCarlino** [comment]
![image](https://user-images.githubusercontent.com/1388608/82830424-54420400-9e7b-11ea-89af-5c6b2839d5c9.png)
In the screenshot above, I hit the "SAVE" button at 11:30am on May 25th 2020

**Comment by roryaronson** [comment]
I was able to reproduce this when we were debugging this morning with a simplified setup that seems to indicate it is not an issue with just near-future events, or anything to do with groups or variables.
- Bot set to Hawaii time, computer set to California time
- Trying to schedule a sequence event with no variable
- Date set to a year a month and two days in the future
- Time set in the future for both local and bot timezones
<img width="1440" alt="Screen Shot 2020-05-25 at 10 00 48 AM" src="https://user-images.githubusercontent.com/5524043/82832174-353d7500-9e6f-11ea-885e-fe24798624e2.png">
