### ISSUE TITLE
Report status on Sync button

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/farmbot-web-app#181]
1. User clicks "Sync" button
2. Button's text changes from "Sync" to "Syncing"
3. Buttons text temporarily changes to "Synced"
4. Button returns to normal

**Comment by roryaronson** [comment]
I think once the device has synced, the button's text should change to "synced" and stay that way until the user makes further changes to their schedule from within the web app. If they make any changes that need to be synced, button changes to say "sync".

**Comment by roryaronson** [comment]
![sync button 1](https://cloud.githubusercontent.com/assets/5524043/7659958/d2e78048-fafa-11e4-87ed-153e9f68f610.png)

**Comment by roryaronson** [comment]
This is working great on production! :tada:
