### ISSUE TITLE
Improve OS Download Page

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1833]
Some users may be downloading the wrong version of FBOS for their kit resulting in boot failures. Adding a photo popup of the Pi may help users make the correct download choice.

![Download FBOS](https://user-images.githubusercontent.com/5524043/84963359-086f2d00-b0be-11ea-8317-72c35ac976b1.jpg)

![Pi3](https://user-images.githubusercontent.com/5524043/84963373-12912b80-b0be-11ea-87b3-6abf9c52b4c9.JPG)

![Pi Zero W](https://user-images.githubusercontent.com/5524043/84963370-0efda480-b0be-11ea-9e0f-34fb8fc5eb54.jpeg)

**Comment by RickCarlino** [comment]
Other ideas:

 * Only show one download link at a time. Prompt the user with a photo of the two boards side-by-side and do not show the download link until one of the photos are clicked.

**Comment by roryaronson** [comment]
Fixed via #2326
