### ISSUE TITLE
MOVE command - UI

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1891]
This is a working document for the new **MOVE** command which should eventually support:
- Current **MOVE TO** command features
- **VARIANCE** (also known as "random jitter")
- **AXIS DISABLE**
- **SAFE Z** (Breaking one movement into three: Z only, X and Y only, Z only)
- Field variables (soil height, plant height, safe Z height, etc)
- Field formulas (plant height * 1.2)
- Deprecating move_relative by allowing MOVE command with no coordinates, only offsets
- **SPEED** inputs limited between 1 and 100% (#1488)

[Early mockup](https://docs.google.com/drawings/d/1MBP0XzJclvdyZe1X9s8jsfAS4ysTvcZdx7mRfnPzfTM/edit?usp=sharing)

**Comment by roryaronson** [comment]
- [Data structure brainstorm](https://gist.github.com/RickCarlino/94127100cb07b9d54fd80cd6c8ba1b20)
- [Updated mockup](https://docs.google.com/drawings/d/1Q3GpjTuCC8WwzOvTp_ZwH1AQ-ejZd1RoHZmWK8-GwzY/edit?usp=sharing)

**Comment by RickCarlino** [comment]
v2 Draft interfaces CC @gabrielburnworth 

```typescript

// This list will grow and shrink over time.
// Write systems in a way that they will not crash when the
// list changes. Gracefully ignore unknown values.
type SPECIAL_VALUE =
  | "current_location"
  | "safe_height"
  | "soil_height";

type ALLOWED_AXIS =
  | "all"
  | "x"
  | "y"
  | "z";

type LocationLike =
  | Coordinate
  | Point
  | Tool
  | Identifier
  | Lua;

type NumberLike =
 | Numeric
 | Lua
 | Random;

type AxisOperand =
 | LocationLike
 | NumberLike
 | SpecialValue
 | None;

interface None {
  kind: "none",
  args: {};
}

interface SpecialValue {
  kind: "special_value",
  args: {
    label: string; // Actually it is SPECIAL_VALUE, but will widen to `string`.
  }
}

interface AxisOverwrite {
  kind: "axis_overwrite",
  args: {
    axis: ALLOWED_AXIS;
    axis_operand: AxisOperand;
  }
}

interface AxisAddition {
  kind: "axis_addition",
  args: {
    axis: ALLOWED_AXIS;
    axis_operand: AxisOperand;
  }
}

interface SpeedOverwrite {
  kind: "speed_overwrite",
  args: {
    speed: Numeric | Lua
  }
}

// Do we actually need a "modifier" concept or is SafeZ the
// only one?
interface SafeZ {
  kind: "safe_z",
  args: {}
}

interface Move {
  kind: "move",
  args: {},
  body?: (AxisOverwrite | AxisAddition | SpeedOverwrite | SafeZ)[]
}
```

**Comment by roryaronson** [comment]
QA notes:
- [ ] Update **SAFE Z** tooltip to:
```
If enabled, FarmBot will:
1. Move Z to the Safe Z height
2. Move X and Y to the new location
3. Move Z to the new location
```
- [ ] Adding an **OFFSET** or **VARIANCE** of some value, then changing it back to `0` doesn't remove the `axis_addition` block from the celeryscript. While FBOS would operate as expected, should that block be cleaned up?
- [ ] Selecting a Location that is a Plant, Variable, Point, Weed, or Slot results in three `axis_overwrite` blocks in the celeryscript (one for `"axis": "x"`, `"axis": "y"`, and `"axis": "z"`). Should we remove `"all"` from the `ALLOWED_AXIS` type if we don't really plan on using it?
- [ ] Selecting "Offset from current location" but then keeping all or some **OFFSET** values as `0` still results in `axis_addition` blocks for all three axes. Are these necessary? Or should they only be added for non-zero offset values? Seems like the same behavior as two bullets up.
- [ ] Setting **SPEED** for any one axis results in a `speed_overwrite` block that is not axis specific. Upon saving, the **SPEED** for all three axes is overwritten with only one of the custom values.
- [ ] Change `fa-repeat` to `fa-undo`
- [ ] Increase font size of LUA to `.75rem` and change padding to `.2rem .4rem`
- [ ] Change "LUA" to "f(x)"?
- [ ] `text-align: center` [+] and remove left padding to better center the button in the available space.
