### ISSUE TITLE
clicking on dashboard buttons causes other html features to "giggle".

### ISSUE THREAD

**Issue by elbow-jason** [FarmBot/farmbot-web-app#193]
At the route `/dashboard#/movement` in the 'Move' panel, clicking on buttons 'giggles' other html features on the page. This may be a CSS issue.

**Comment by roryaronson** [comment]
That's probably my fault. I did all of the frontend styling (as my first software project ever). We're planning to do a frontend refactor in the coming months, and may consider switching to bootstrap from foundation.
