### ISSUE TITLE
Soil height

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#1938]
## Goal
Users should be able to specify the height of their soil so they can:
- Easily plant seeds at the Soil Height minus an offset of Seed Depth
- Water, take photos, measure soil moisture, etc offset from the soil surface
- Abate weeds with movements based on soil height

[Mockup.pdf](https://github.com/FarmBot/Farmbot-Web-App/files/5144413/Points.Panel.v2.with.Soil.Height.pdf)

## MVP

User can specify one soil height that is used globally. (**SHIPPED October 2020**)

## Phase 2
User can specify many soil heights via the points panel as shown in the mockup. FBOS could calculate Soil Height at new locations using either a ray tracing algorithm or simply use the height from the closest available measurement.

Nice-to-haves like plants and weeds being created at soil height rather than Z = 0.

## Phase 3
Distance sensing hardware, a button tool, and/or stereoscopic tricks could be used to automatically gather soil height measurements.

Nice-to-haves such as elevation lines, an ability to mouseover any location and get a calculated height, etc.

**Comment by mdingena** [comment]
When soil height is measured via a points grid, it should be possible to interpolate the soil height at any location by drawing a triangular plane between the three closest soil height measurements surrounding the current position. It wouldn't strictly be accurate as there can be bumps and dips everywhere, but short of measuring soil height every centimeter or so, this approximation is probably "good enough".

```
 X , Y
100,200 →  a_____b  ← 300,200
           |     |
           |     |
           |     |
           |   + |  ← 250,280 (UTM position)
           |     |
100,350 →  d‾‾‾‾‾c  ← 300,350
```
Find the triangle in which the UTM currently resides.
```
                 b  ← -515 mm
                /|
               / |
              /  |
             / + |
            /    |
-498 mm →  d‾‾‾‾‾c  ← -505 mm
```
Find the `z` of the soil height based on the UTM's `x` and `y` position using barycentric coordinates.
```javascript
const calculateZ = (p1, p2, p3, utmX, utmY) => {
  const det = (p2.y - p3.y) * (p1.x - p3.x) + (p3.x - p2.x) * (p1.y - p3.y);

  const lambda1 = ((p2.y - p3.y) * (utmX - p3.x) + (p3.x - p2.x) * (utmY - p3.y)) / det;
  const lambda2 = ((p3.y - p1.y) * (utmX - p3.x) + (p1.x - p3.x) * (utmY - p3.y)) / det;
  const lambda3 = 1.0 - lambda1 - lambda2;

  return lambda1 * p1.z + lambda2 * p2.z + lambda3 * p3.z;
}

calculateZ({ x: 300, y: 200, z: -515 }, {x: 300, y: 350, z: -505 }, { x: 100, y: 350, z: -498 }, 250, 280);
// → -507.9166666666667
```
```
                 b  ← -515 mm
                /|
               / |
              /  |
             / + |  ← -507.92 mm (rounded)
            /    |
-498 mm →  d‾‾‾‾‾c  ← -505 mm
```

**Comment by roryaronson** [comment]
Thanks for the input @mdingena! I was describing in our Slack channel a few weeks ago using a "weighted average" method, but cool to know the more precise mathematical phrase is "barycentric coordinates" 😉
