### ISSUE TITLE
Self-host issue building environment

### ISSUE THREAD

**Issue by stre1026** [FarmBot/Farmbot-Web-App#2100]
I'm following the "ubuntu_example.sh" guide on a fresh Ubuntu 20 server. When I get to line 51 of the ubuntu_example.sh script,  and run "sudo docker-compose run web bundle install", I get an error that says "Your Ruby version is 2.7.2, but your Gemfile specified ~> 3.0.0" and I cannot go any further. The containers don't load and I can't do anything else. I've rebuilt the server a few times to make sure I didn't miss anything.

**Comment by gabrielburnworth** [comment]
For reference, this is line 51: https://github.com/FarmBot/Farmbot-Web-App/blob/c811d463154d5af23d7317a7643fc7dacbea0550/ubuntu_example.sh#L51

I've fixed the issue during upgrades by running https://github.com/FarmBot/Farmbot-Web-App/blob/c811d463154d5af23d7317a7643fc7dacbea0550/ubuntu_example.sh#L85

but I'm not sure why that error would happen on fresh builds.

**Comment by stre1026** [comment]
This seems to have worked! Thank you!!
