### ISSUE TITLE
Web-App local host issue: "Invalid Version: undefined"

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/Farmbot-Web-App#2108]
When running the command `sudo docker-compose run web rake assets:precompile` from the ubuntu_example.sh file, the following error comes up:

![image](https://user-images.githubusercontent.com/23129562/110965220-469b3380-8354-11eb-8dd7-de48f138fe68.png)

There seems to be an issue with Parcel on the current version 1.12.4. (https://github.com/parcel-bundler/parcel/issues/5943)
I went back to 1.12.3 which "solved" the problem, at least as a workaround.

**Comment by RickCarlino** [comment]
Thanks for this very descriptive bug report @AscendFB .

I have put this item on my TODO list.

**Comment by AscendFB** [comment]
Issue got fixed with parcel-bundler v1.12.5, tried it on my local repo. I'll close this issue right away.
https://github.com/parcel-bundler/parcel/issues/5943#issuecomment-799899064
