### ISSUE TITLE
Redesign Add Command button

### ISSUE THREAD

**Issue by roryaronson** [FarmBot/Farmbot-Web-App#2292]
Redesign the Add (first) Command button to look like a generic placeholder sequence step. Users should be able to click anywhere on the step to add their first command.

<img width="529" alt="Screen Shot 2021-12-09 at 5 07 30 PM" src="https://user-images.githubusercontent.com/5524043/146276983-990d36c0-98fa-4dbe-9f84-77a0b4997cdd.png">

**Comment by ejgonzalez17** [comment]
Hi, I will like to work in this Issue .

**Comment by roryaronson** [comment]
Awesome, thanks for stepping up @ejgonzalez17! Let us know if you have any questions about the ticket :)

**Comment by roryaronson** [comment]
@ejgonzalez17 have you made any progress or hit any roadblocks on this ticket? Do you have any questions that we may be able to help you with?

**Comment by roryaronson** [comment]
@ejgonzalez17 I am going to un-assign this issue for now. If you would still like to make a contribution please let us know with either a pull request or by asking the specific questions you need answered to complete the work. Thanks!

**Comment by roryaronson** [comment]
Superseded by #2328
