### ISSUE TITLE
how to adjust the speed of farmbot after  i change the setting and no speed increase?

### ISSUE THREAD

**Issue by alkhlama** [FarmBot/Farmbot-Web-App#2296]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce

# Results of `git log -1`

Run `git log -1` and paste the results here.

**Comment by RickCarlino** [comment]
FarmBot, Inc. does not provide setup support to DIY users that have not purchased a full kit, nor is the Github page for the Web App the correct place to ask setup-related questions. Please [ask your question on the forum](https://forum.farmbot.org/) instead.
