### ISSUE TITLE
A proposal to write the API codebase in a Node.js backend server

### ISSUE THREAD

**Issue by MikeTeddyOmondi** [FarmBot/Farmbot-Web-App#2305]
I want to propose that FarmBot's API codebase be rewritten in a new repo with a Javascript backend with all the same functionality. For this to allow other developers to create new repositories with other backend tech stacks also.

**Comment by RickCarlino** [comment]
@MikeTeddyOmondi FarmBot is an Open Source project that can be freely forked and modified. I am happy to answer any questions you have about the codebase as you go along, though I have no interest in officially migrating the project away from Ruby on Rails.

**Comment by RickCarlino** [comment]
@MikeTeddyOmondi FarmBot is an Open Source project that can be freely forked and modified. I am happy to answer any questions you have about the codebase as you go along, though I have no interest in officially migrating the project away from Ruby on Rails.
