### ISSUE TITLE
# events not working!! 

### ISSUE THREAD

**Issue by chanwitG** [FarmBot/Farmbot-Web-App#2332]
I have tried to set a farm event for waterings using both regimens and sequences but I cannot seem to get any event to start. When I first schedule it, I get a message at the bottom of my screen “Farm Event will run in 2 minutes”. So I wait 2 minutes and nothing. I look at the scheduled event with the title name I had previously set, and now it says “empty” Will post screenshots soon. Please help!

**Comment by roryaronson** [comment]
Your issue appears to be isolated to your device and user account. Please email support@farm.bot with additional details (screenshots, etc) and we can help troubleshoot your specific setup.

**Comment by chanwitG** [comment]
and im try to move sequence or command  farmbot to auto event  it's not working it say empty 
![image](https://user-images.githubusercontent.com/101252187/157786156-25052129-6d8b-46d9-8c11-318fc9cda9eb.png)
![image](https://user-images.githubusercontent.com/101252187/157786207-0067114a-b2a7-4106-a924-f06fa85faf1a.png)
![image](https://user-images.githubusercontent.com/101252187/157786234-944ecc49-1e4b-4770-a43a-7bfd822165c2.png)

**Comment by roryaronson** [comment]
If the current time is a few minutes or more later than a past event instance, the event will say *Empty*. Once you refresh the page event instances in the past will not longer be displayed.

I recommend going through our [software documentation hub](https://software.farm.bot/) page by page to learn how to make sequences, regimens, and events. If you have further issues, please navigate to the [in-app support panel](https://my.farm.bot/app/designer/support) and either email us or use the feedback form.
