### ISSUE TITLE
Multiple Garden Beds

### ISSUE THREAD

**Issue by jpmaidment** [FarmBot/Farmbot-Web-App#2354]
Hi,

I'm wanting to use the web app to manage my non-farmbot garden beds, so I can mange them all in the one place. Is this something that already exists? or something that can be added?

**Comment by roryaronson** [comment]
Managing multiple garden beds is not a current feature, though you could set your single FarmBot bed to have a really large [**MAP SIZE**](https://my.farm.bot/app/designer/settings?highlight=map_size) in the app and use the extra map space to add other plants and keep track of them.

In real life, the FarmBot would only be able to access the corner of the garden determined by the [**AXIS LENGTH**](https://my.farm.bot/app/designer/settings?highlight=set_axis_length) settings. You would need to be careful to never instruct the FarmBot to try to reach one of the plants outside this area or the sequence will fail.

For example: these Spinach plants would be in the FarmBot reachable area defined by the dotted lines (axis lengths), while the Beets might be in a different garden bed but still in the map.

<img width="1145" alt="Screen Shot 2022-05-27 at 4 45 46 PM" src="https://user-images.githubusercontent.com/5524043/170800780-525f3624-5033-49e6-86a5-4e84506ca187.png">

**Comment by jpmaidment** [comment]
Great idea! Thank you!
