### ISSUE TITLE
Webapp shows farmbot as offline (but it is switched on)

### ISSUE THREAD

**Issue by kulbir-ahluwalia** [FarmBot/Farmbot-Web-App#2393]
Hi,

The web app portal shows all of our farmbots as offline and disconnected. 
![offline_farmbot](https://user-images.githubusercontent.com/55640820/202826804-812e13be-99d6-405d-b885-35c700231390.png)

We are not able to control any of the farmbots using the webapp. Although we are able to add/edit/delete gardens using the python package. (We are not able to move them using the python package)

Could you please help us figure out what might be wrong on our end? Please let us know. Thanks!

**Comment by roryaronson** [comment]
Hi @kulbir-ahluwalia, according to the connectivity Diagnosis shown in your screenshot, it appears your FarmBot and your computer are connected to a network that is blocking traffic through port 3002. Please send [this document](https://software.farm.bot/docs/for-it-security-professionals) to your IT department and have them unblock port 3002, and all other ports that FarmBot requires.
