### ISSUE TITLE
Found this conflicting local requirement.

### ISSUE THREAD

**Issue by sportscar** [FarmBot/Farmbot-Web-App#2441]
Dear All, 

When I run sudo docker compose run web rake assets:precompile the compiler showed a warning:

      | @parcel/resolver-default: Could not find module "punycode" satisfying ^1.4.1.
      | 
      | 
      |   /farmbot/package.json:65:5
      |     64 |     "url": "0.11.1",
      |   > 65 |     "punycode": "2.3.0",
      |   >    |     ^^^^^^^^^^ Found this conflicting local requirement.
      |     66 |     "querystring-es3": "0.2.1",
      |     67 |     "react": "18.2.0",

After checking all dependency, I found that npm url 0.11.1 was using punycode 1.4.1 while others

`were using punycode 2.3.0. 
├─┬ coveralls@3.1.1
│ └─┬ request@2.88.2
│   └─┬ tough-cookie@2.5.0
│     └── punycode@2.3.0 deduped
├─┬ eslint@8.43.0
│ └─┬ ajv@6.12.6
│   └─┬ uri-js@4.4.1
│     └── punycode@2.3.0 deduped
├─┬ jest-environment-jsdom@29.5.0
│ └─┬ jsdom@20.0.3
│   ├─┬ tough-cookie@4.1.3
│   │ └── punycode@2.3.0 deduped
│   └─┬ whatwg-url@11.0.0
│     └─┬ tr46@3.0.0
│       └── punycode@2.3.0 deduped
├── punycode@2.3.0
└─┬ url@0.11.1
  └── punycode@1.4.1
'

Though the website finished building, this made the parcel take a really long time to load.

How can I resolve this.

**Comment by gabrielburnworth** [comment]
After the latest updates, this warning should no longer appear.
