### ISSUE TITLE
Max. WLANs in scan drop down

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/Farmbot-Web-App#340]
Hi all, 
could it be that you limited the max. number of WLANs shown in the scan drop down menu during config? Mine only appears from time to time but there are more than 20 WLANs around...

**Comment by RickCarlino** [comment]
@ConnorRigby Any idea on this one?

**Comment by ConnorRigby** [comment]
They are not sorted or filtered at all. It is parsed via the raw output of `iw list` currently - which extends the Linux kernel Wireless Supplicant. If your WiFi is not on the list, the RPI just can not see it. This is likely a quality, or distance problem. If there are many SSIDs around you it is likely that the channel your network is on is crowded.
