### ISSUE TITLE
Error of moving components in a sequence

### ISSUE THREAD

**Issue by Klimbim1** [FarmBot/Farmbot-Web-App#342]
If I duplicate a component (move absolute) in a sequence and want to drag & drop it to another location, sometimes it gets duplicated when doing this. Sometimes not...

**Comment by roryaronson** [comment]
We're aware of an issue where if you drag an existing Step to the bottom "Drag Command Here" area, then it will be duplicated when it should not. We'll let you know when this is fixed.

**Comment by RickCarlino** [comment]
@Klimbim1 Is this still an issue?
