### ISSUE TITLE
NO_EMAILS does not disable email verification

### ISSUE THREAD

**Issue by yyzzz6000** [FarmBot/Farmbot-Web-App#419]
# Expected Behavior
Set NO_EMAILS in application.yml to be TRUE, expect no email verification required
# Actual Behavior
The local server still asks me for email verification
# Steps to Reproduce
1. set NO_EMAILS to TRUE in application.yml, save the file.
2. npm run dev
3. goto localhost:3000 and create a new user count

**Comment by RickCarlino** [comment]
Thanks for letting us know. I will take a look tomorrow morning.

**Comment by RickCarlino** [comment]
@yyzzz6000 I have identified the cause of the failure and should have a fix in a few hours.

**Comment by RickCarlino** [comment]
@yyzzz6000 Does everything work now?

**Comment by yyzzz6000** [comment]
Hello, Rick,
Yes! We have updated the environment right after the fix and I can skip verification now. Sorry for the late response, I missed the notification until now.  Thank you for the quick fix and have a good day.
