### ISSUE TITLE
Generating HTML Pages

### ISSUE THREAD

**Issue by JordanOPStudent** [FarmBot/Farmbot-Web-App#456]
When generating the home page it seems like it times out after a period of time. The client ends up timing out eventually and the terminal spews out the follow.
```
16:32:07 rails.1   | Processing by DashboardController#front_page as HTML
16:32:09 rails.1   |   Rendering dashboard/front_page.html.erb
16:32:10 rails.1   |   Rendered dashboard/_addons.html.erb (111.0ms)
16:32:10 rails.1   |   Rendered dashboard/_common_assets.html.erb (601.6ms)

16:34:27 rails.1   |   Rendered dashboard/front_page.html.erb (137438.4ms)
16:34:32 rails.1   | Completed 500 Internal Server Error in 145399ms
16:34:32 rails.1   |
16:34:32 rails.1   |
16:34:34 rails.1   |
16:34:34 rails.1   | ActionView::Template::Error (Could not load manifest from webpack-dev-server at http://localhost:3808/webpack/manifest.json - is it running, and is stats-webpack-plugin loaded? (original error Net::ReadTimeout)):
16:34:34 rails.1   |     4:     <%= render "common_assets" %>
16:34:34 rails.1   |     5:   </head>
16:34:34 rails.1   |     6:   <body>
16:34:34 rails.1   |     7:     <%= javascript_include_tag *webpack_asset_paths("front_page") %>
16:34:34 rails.1   |     8:   </body>
16:34:34 rails.1   |     9: </html>
16:34:34 rails.1   |
16:34:34 rails.1   | app/views/dashboard/front_page.html.erb:7:in `_app_views_dashboard_front_page_html_erb__3034589854009657370_49699940'
16:34:34 rails.1   | app/controllers/dashboard_controller.rb:18:in `block (2 levels) in <class:DashboardController>'
```

Checking into stats-webpack-plugin it appears that the plugin requires an older version of webpack while the package.json requires 3.5.5. I'm not entirely sure if I may have messed up somewhere in the installation process or if this was just an oversight.

**Comment by RickCarlino** [comment]
@JordanOPStudent Interesting. I have not seen this one before.

A few questions:
 * What were the exact commands you entered in to the terminal prior to seeing this message?
 * Is anything using or blocking port 3808 on your machine? Does `http://localhost:3808` show anything in a browser?
 * What version of node are you running?

**Comment by JordanOPStudent** [comment]
We managed to resolve the issue. Apparently 1GB of RAM to host it was not enough and had to expand it to 4GB.
