### ISSUE TITLE
Logs showing problem

### ISSUE THREAD

**Issue by enderahmetyurt** [FarmBot/Farmbot-Web-App#464]
Hi,

I have 35 entries for Log table but I cannot see any logs on the navigation bar.

Are there any problem in here?

Cheers.

![screen shot 2017-09-22 at 15 37 22](https://user-images.githubusercontent.com/447588/30744703-fed689da-9fab-11e7-8d8d-e11fa1643fc3.png)

![screen shot 2017-09-22 at 15 35 51](https://user-images.githubusercontent.com/447588/30744687-eb15a926-9fab-11e7-8c76-fcb18f358b1a.png)

**Comment by RickCarlino** [comment]
@enderahmetyurt A few questions:

 1. Are you sure you are logged in as device `2`? Running `store.getState().auth.user.device_id` in the JS console will help.
2. Did you refresh the page? We don't support realtime messages from the API --> browser (we _do_ support realtime messages from FarmBot --> broswer, though)


Also, I noticed that the log you pulled up was of type "debug". We typically [don't store "debug" or "fun" messages](https://github.com/FarmBot/Farmbot-Web-App/blob/master/app/controllers/api/logs_controller.rb#L20) to the database. I don't think this has any bearing on the current issue, but I thought it was worth mentioning if you are planning on modifying code related to logs.

**Comment by enderahmetyurt** [comment]
Yes, I saw it. Thanks for help. Sorry for that silly question. I am newbie on Farmbot 😳

**Comment by RickCarlino** [comment]
No worries! Glad you found the fix.
