### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by Abdullah7528** [FarmBot/Farmbot-Web-App#486]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce

**Comment by Abdullah7528** [comment]
![error](https://user-images.githubusercontent.com/31927817/31234385-a67e014e-a9a3-11e7-91c3-ecc15df4034b.PNG)

**Comment by RickCarlino** [comment]
@Abdullah7528 Please show me output for the following commands:

`rails s`
`npm run webpack`

**Comment by Abdullah7528** [comment]
This is my ultimate error after executing all the steps.
Thankyou
