### ISSUE TITLE
Problem with docker?

### ISSUE THREAD

**Issue by IsmaelFelix** [FarmBot/Farmbot-Web-App#517]
Im trying to program my farmbot for the first time and im following the documentation of the Web app but at the time that i run the command rails mqtt:start i get this message (but im login in docker (i think im)):

"Unable to find image 'farmbot-mqtt:latest' locally
docker: Error response from daemon: pull access denied for farmbot-mqtt, repository does not exist or may require 'docker login'."

**Comment by RickCarlino** [comment]
@IsmaelFelix Are you able to run other Docker images on the machine?

You can verify by running:

```
sudo docker run hello-world
```

**Comment by RickCarlino** [comment]
@IsmaelFelix I just provisioned a new Ubuntu 17.10 VM to make sure the Docker image is running as expected.

Everything worked fine. I used [these steps](https://gist.github.com/RickCarlino/48b0362ccb82dffe5d4a292ee1cc00d2) to get everything set up without any issues.

I think you may have a local configuration or network issue on your machine. How did your setup compare to the steps show in the link above?
