### ISSUE TITLE
MQTT : rails mqtt:start problem

### ISSUE THREAD

**Issue by Bunraku** [FarmBot/Farmbot-Web-App#528]
Hi,
We are a group of student working on Farmbot.
We would like to have our own Farmbot web app based on our Server.
For this, we are using a Virtual Machine
We are having issues when typing the rails mqtt:start command :
It seems that the Erlang version used on our VM is not the same as the one used for the Farmbot.
Enclosed is our log file.

We would also like to know what version of Erlang is used for Farmbot.?

Thanks in advance
[log.txt](https://github.com/FarmBot/Farmbot-Web-App/files/1461601/log.txt)

**Comment by RickCarlino** [comment]
@Bunraku I just responded to this [question on the forum](https://forum.farmbot.org/t/mqtt-rails-mqtt-start-problem/2850/2), but perhaps Github is a more appropriate place to have this discussion.

My main questions were:


 * Is your server running any special code modifications other than the typical setup instructions?
 * What version of the app are you running? You can find out by running `git log -1 --abbrev-commit` from the Web App directory.

**Comment by Bunraku** [comment]
Thanks for your reply!
- Atm there is no code modification
- Here is the result of the request : 

- commit 295d93c
Merge: c6d0502 33e5c87
Author: Rick Carlino <RickCarlino@users.noreply.github.com>
Date:   Sun Oct 22 14:11:48 2017 -0500
    Merge pull request #511 from RickCarlino/sunda
    Dep upgrades

**Comment by RickCarlino** [comment]
@Bunraku You may be running a slightly outdated version of the app. We were still working out some bugs with the new broker at that time (October 22). Please try the following from the command line to upgrade to the latest stable version:

```
git pull origin master
yarn install
bundle install
rails db:migrate
rails mqtt:start
```

**Comment by Bunraku** [comment]
We are going to try it as soon as possible and we will come back to you, thanks for your answer!

**Comment by Bunraku** [comment]
:1st_place_medal: We have done those steps and it's working now. Thanks for your help !

**Comment by RickCarlino** [comment]
I'm lad you got it working!
