### ISSUE TITLE
White screen after login

### ISSUE THREAD

**Issue by Bunraku** [FarmBot/Farmbot-Web-App#530]
Hi again! :) 
We have a white screen after login to our web app on our own server.
![image](https://user-images.githubusercontent.com/3373580/32956135-4150d094-cbb8-11e7-8bd8-128a806adb89.png)
How can we fix this?
Thanks :)

**Comment by RickCarlino** [comment]
This might just be a strange inconsistent state from the upgrade.

A few things to try:

1. Run `localStorage.clear()` and `sessionStorage.clear()` in the Javascript console `ctrl + shift + J`
2. Hard refresh with `ctrl + shift + r`.

If that does not work:

1. What are you using as your `MQTT_HOST`, `API_HOST`, `MQTT_WS` variables in `config/application.yml`? Make sure it is a real host name and not `localhost`.
2. How did you start the server? Did you use `rails api:start`?

**Comment by Bunraku** [comment]
So we did your steps. Still not working :/
We have checked and MQTT_HOST and API_HOST are real host names. We deleted the line MQTT_WS as we are self hosting users.

We started the server using rails api:start.

Do you know where the problem comes from ?

Thank you in advance :)

**Comment by RickCarlino** [comment]
@Bunraku I am still unsure of why this would be happening, but it is related to `webpack` not building the javascript files correctly.

Can you please try running the following:

```
git pull origin master
bundle install
yarn install
```

And then show me the output of this command:
```
./node_modules/.bin/webpack-dev-server --config config/webpack.dev.js --host 0.0.0.0
```

Also, if you are just trying to get a server running and do not need a local software development setup, you _might_ be able to fix the problem simply by running:

```
npm run build
```

**Comment by Bunraku** [comment]
There it is : 
[log.txt](https://github.com/FarmBot/Farmbot-Web-App/files/1491660/log.txt)

**Comment by Bunraku** [comment]
Still not working :/ There it is : 
[log.txt](https://github.com/FarmBot/Farmbot-Web-App/files/1495951/log.txt)
We would like our local development setup,but thank you for the command, it could be useful sometimes :)

**Comment by RickCarlino** [comment]
@Bunraku There's not enough information to know from the log and screenshot provided. Something is preventing Webpack from loading.

Are there any other settings on your system that may be different from a typical Ubuntu developer setup? Are you running any software that is using or blocking port `3808`? Have you tried running it in Chrome?

If it is urgent, you may want to try running [these steps](https://github.com/FarmBot/Farmbot-Web-App/blob/master/ubuntu_example.sh) on a fresh installation of Ubuntu 17. This would remove the possibility of a bad setup dependency on your local machine.
