### ISSUE TITLE
take-photo issue

### ISSUE THREAD

**Issue by cyriacr** [FarmBot/Farmbot-Web-App#575]
# Expected Behavior
display photo after received "Farmbot [take-photo] completed!" notification

# Actual Behavior
display nothing

# Steps to Reproduce
self hosting with test environment, without GCP storage settings.

farmbot-web-frontend 1.1.0
farmbot OS 5.0.9
ran on Ubuntu 16.04 

application.yml:
[application.yml.txt](https://github.com/FarmBot/Farmbot-Web-App/files/1558784/application.yml.txt)

**Comment by RickCarlino** [comment]
@cyriacr It sounds like your background workers (which do image processing outside of the HTTP server) are not running. There isn't enough information to say, though. Your application.yml looks fine.

A few questions:

1. What version of the API are you running? Please upgrade via `rails api:upgrade` to make sure you are on the latest version.
2. What do you see when you run `rails api:start | grep "worker.1" --line-buffered`?

**Comment by cyriacr** [comment]
Hi Rick,

I did a fresh installation via my script here: https://github.com/cyriacr/fwa-quick-install

I think it's already the latest version, with "farmbot": "5.2.0-rc7" in package.json

And here is my work.1 log

[worker.1.log.txt](https://github.com/FarmBot/Farmbot-Web-App/files/1560227/worker.1.log.txt)

**Comment by RickCarlino** [comment]
@cyriacr `rc7` might be too new of a release (that's our unstable staging branch).

I would recommend starting over with the stable `master` branch. Farmbot js should be at `5.0.2` as of 15 December 2017. We should have a new release out in the next week or so.

I noticed in your script that you set `RAILS_ENV=test`. I would *not recommend* that. Please run the app in `production` or `development` mode. I think `development` mode would be best for now, as it provides better error messages. The `test` environment is intended for automated unit tests only.

**Comment by cyriacr** [comment]
@RickCarlino I've cloned from master branch and changed RAILS_ENV to development but still having same issue in take-photo issue.
I'll pause testing current version and wait for new release out.

**Comment by rdegosse** [comment]
Hi,
Same issue in 6.1.0...
Test KO with no GCS_BUCKET config (local) and with a personal GCS BUCKET.
Test Ok with same SD card (F OS 5.0.9) and my.farmbot.io
