### ISSUE TITLE
Path error ubuntu install procedure

### ISSUE THREAD

**Issue by nicmel** [FarmBot/Farmbot-Web-App#634]
# Expected Behavior

the source command "source /usr/local/rvm/scripts/rvm" shoud find this file

# Actual Behavior

it does not find it. The path does not exist.
I can find a file in ".rvm/scripts/rvm" but I don't know if it's the right one

# Steps to Reproduce

By folowing the install procedure on ubuntu server

**Comment by RickCarlino** [comment]
Hi @nicmel,

I will investigate the issue now. Thanks for bringing this to our attention.

**Comment by RickCarlino** [comment]
@nicmel 

I was not able to reproduce this issue on a fresh installation of Ubuntu 17. All of the steps in [ubuntu_example.sh](https://github.com/FarmBot/Farmbot-Web-App/blob/staging/ubuntu_example.sh) related to RVM seem to be working.

Some other things you could try:

 * Make sure you are running Ubuntu 17x64
 * Make sure RVM installs completely. Feel free to raise an issue if installation fails.
 * Make sure you don't have any special environment changes related to `ruby` or `rvm`.

The only issue that I noticed while installing on a new machine was that the order of `rails mqtt:start` and `rails api:start` were in the wrong order.

Older versions of the app allowed developers to start the API and MQTT server in  any order, but new versions require the API to come online before the MQTT server may start.

I've fixed the issue in [this pull request](https://github.com/FarmBot/Farmbot-Web-App/pull/637). Thanks for bringing it to our attention!

Will re-open the issue if you can provide more information about your environment / RVM setup.
