### ISSUE TITLE
javascript security policy

### ISSUE THREAD

**Issue by nicmel** [FarmBot/Farmbot-Web-App#636]
# Expected Behavior

Accessing the web page X.X.X.X:3000

# Actual Behavior

Blank page, firefox and chrome debug gives:
x.x.x.x:3808/webpack/front_page.js (« script-src http://x.x.x.x:3000 'unsafe-eval' 'unsafe-inline' http://cdnjs.cloudflare.com chrome-extension: http://localhost:3808 »).

# Steps to Reproduce

following the ubuntu procedure on ubuntu server.

**Comment by RickCarlino** [comment]
@nicmel Thanks for finding this bug. The fix is in [Pull Request #637](https://github.com/FarmBot/Farmbot-Web-App/pull/637)
