### ISSUE TITLE
Unable to increase wifi timeout limit

### ISSUE THREAD

**Issue by mdchia** [FarmBot/Farmbot-Web-App#652]
# Expected Behavior

Changing connection attempt period in Device > Power and Reset > CONNECTION ATTEMPT PERIOD should save as normal (along with the other device settings)

# Actual Behavior

Doesn't update, error message in logs: 
`[farmbot name] got an invalid configuration in Configuration tracker: "network_not_found_timer"`

# Steps to Reproduce

Using my.farmbot.io servers
Farmbot OS Version 5.0.6
Firmware: Arduino/RAMPS (Genesis v1.2)

Connection attempt period should be empty. Change this to any actual numerical value (I used 60 minutes). Error should trigger when next attempting to sync device or sooner.

**Comment by gabrielburnworth** [comment]
Your FarmBot OS version is outdated and will not work with this new feature. Please update to the latest FarmBot OS, currently v6.1.2.
