### ISSUE TITLE
Can't delete weeds

### ISSUE THREAD

**Issue by AscendFB** [FarmBot/Farmbot-Web-App#694]
# Expected Behavior
Detected weeds get erased from the plant designer.
# Actual Behavior
Toast error message:
![image](https://user-images.githubusercontent.com/23129562/36970796-09876176-206a-11e8-87cc-99e1b2bfd367.png)

Chrome console error message:
![image](https://user-images.githubusercontent.com/23129562/36970766-efc97a62-2069-11e8-9df1-6ac5d0fe327e.png)

# My FarmBot API Version
I'm using my.farmbot.io with OS version 6.2.0.
This function was working days ago. I tried to relog and restart a couple times.

**Comment by RickCarlino** [comment]
@AscendFB I am investigating the issue right now.

On first glance, it looks like one of the points you are trying to delete is in use by a sequence.

If that is the case, I will need to update the error message to be more descriptive.

I will take a deeper look now to see if there are any other factors at play.

**Comment by RickCarlino** [comment]
@AscendFB Please let me know if we need to re-open this issue or not.

**Comment by AscendFB** [comment]
@RickCarlino oh you are absolutely right! Looks like I selected such a weed point accidentally in a sequence without even knowing.
Thanks for the investigation and the updated error message 👍
