### ISSUE TITLE
webpack.1 error

### ISSUE THREAD

**Issue by kc6esn** [FarmBot/Farmbot-Web-App#748]
# Expected Behavior
no error
# Actual Behavior
rails api:start
WARNING: Use strings for Figaro configuration. false was converted to "false".
W, [2018-03-25T23:06:02.169824 #2921]  WARN -- : [SKYLIGHT] [1.5.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
PORT=3000 bundle exec foreman start --procfile=Procfile.dev
23:06:02 rails.1   | started with pid 2931
23:06:02 webpack.1 | unknown command: ./node_modules/.bin/webpack-dev-server --config config/webpack.config.js

# Steps to Reproduce
rails api:start
# My FarmBot API Version
6.2.1
Run `git log -1` and paste the results here
git log -1
commit 6160868077670a11c9bffcc66fb91f826908bd37 (HEAD -> staging, origin/staging, origin/HEAD)
Merge: 4f02e7c1 a7895dfe
Author: Rick Carlino <RickCarlino@users.noreply.github.com>
Date:   Tue Mar 20 10:42:23 2018 -0500

    Merge pull request #738 from RickCarlino/deprecations_ii
    
    Downgrade Webpack, Add Tests

**Comment by kc6esn** [comment]
Ran a new install of the web app but keep on getting this error, Please advise thank you! - Walter

**Comment by RickCarlino** [comment]
@kc6esn It looks like some of your dependencies did not install. Did you run `yarn install` from within the _same directory_ as the FarmBot Web App? If so, what did the output look like?

**Comment by RickCarlino** [comment]
@kc6esn I will need more information to continue troubleshooting this issue. Please let me know if `yarn install` did not fix the issue.

**Comment by kc6esn** [comment]
Hi there Rick, it needed a sudo yarn install. There were also a few other issues with the new Ubuntu 17.10.1 as far as permissions but everything works and the gantry is moving locally now! Thank you again !
