### ISSUE TITLE
Web app issues

### ISSUE THREAD

**Issue by ThomasLegris** [FarmBot/Farmbot-Web-App#777]
Hi,
Thank you for your reply. Unfortunatly, it doesn't work, I had install jest and then run your command.

We have several issues at step 9 and when we launch "rails api:start" and then "rails mqtt:start" . Command  "api:start work" is working sometimes but I will send you the error message. 
The only times when api and mqtt work we have problem of "manifest" when we try to connect to localhost:3000.
![jestfail](https://user-images.githubusercontent.com/34026747/38409825-38b86468-3983-11e8-9279-fb30af1623bf.png)
![npm_run_test](https://user-images.githubusercontent.com/34026747/38409826-38d07f62-3983-11e8-99af-e9165aef1728.png)
![step9error](https://user-images.githubusercontent.com/34026747/38409827-38e74350-3983-11e8-8d70-2699b60b79ac.png)
![mqtt start front page error](https://user-images.githubusercontent.com/34026747/38409836-416348c6-3983-11e8-88a6-9accaf71a91e.png)

Please find attached all the screenshots about our issues. and then -- trace when we want to start api : 
"thomas@toto-pc:~/Farmbot-Web-App$ rails api:start --trace
WARNING: Use strings for Figaro configuration. true was converted to "true".
** Invoke api:start (first_time)
** Invoke environment (first_time)
** Execute environment
W, [2018-04-06T09:30:34.506712 #4930]  WARN -- : [SKYLIGHT] [1.5.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
** Execute api:start
PORT=3000 bundle exec foreman start --procfile=Procfile.dev
09:30:35 rails.1   | started with pid 4939
09:30:35 webpack.1 | started with pid 4941
09:30:35 worker.1  | started with pid 4942
09:30:35 logger.1  | started with pid 4949
09:30:39 rails.1   | WARNING: Use strings for Figaro configuration. true was converted to "true".
09:30:39 logger.1  | WARNING: Use strings for Figaro configuration. true was converted to "true".
09:30:39 worker.1  | WARNING: Use strings for Figaro configuration. true was converted to "true".
09:30:39 logger.1  | [SKYLIGHT] [1.5.1] Unable to start, see the Skylight logs for more details
09:30:39 rails.1   | => Booting Thin
09:30:39 rails.1   | => Rails 5.1.5 application starting in production on http://0.0.0.0:3000
09:30:39 rails.1   | => Run `rails server -h` for more startup options
09:30:39 rails.1   | [SKYLIGHT] [1.5.1] Unable to start, see the Skylight logs for more details
09:30:39 worker.1  | [SKYLIGHT] [1.5.1] Unable to start, see the Skylight logs for more details
09:30:40 rails.1   | Exiting
09:30:40 worker.1  | [Worker(host:toto-pc pid:4942)] Starting job worker
09:30:40 rails.1   | /home/thomas/Farmbot-Web-App/app/lib/key_gen.rb:15:in `initialize': No such file or directory @ rb_sysopen - /keys/production.pem (Errno::ENOENT)
09:30:40 worker.1  | 2018-04-06T09:30:40+0200: [Worker(host:toto-pc pid:4942)] Starting job worker
09:30:40 rails.1   | 	from /home/thomas/Farmbot-Web-App/app/lib/key_gen.rb:15:in `open'
09:30:40 rails.1   | 	from /home/thomas/Farmbot-Web-App/app/lib/key_gen.rb:15:in `generate_new_key'
09:30:40 rails.1   | 	from /home/thomas/Farmbot-Web-App/app/lib/key_gen.rb:28:in `current'
09:30:40 rails.1   | 	from /home/thomas/Farmbot-Web-App/app/controllers/api/public_keys_controller.rb:6:in `<class:PublicKeysController>'
09:30:40 rails.1   | 	from /home/thomas/Farmbot-Web-App/app/controllers/api/public_keys_controller.rb:4:in `<module:Api>'
09:30:40 rails.1   | 	from /home/thomas/Farmbot-Web-App/app/controllers/api/public_keys_controller.rb:3:in `<top (required)>'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:379:in `block in require_or_load'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:36:in `block in load_interlock'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:11:in `loading'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:36:in `load_interlock'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:357:in `require_or_load'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:335:in `depend_on'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:251:in `require_dependency'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:475:in `each'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:475:in `block in eager_load!'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:473:in `each'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:473:in `eager_load!'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:354:in `eager_load!'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/application/finisher.rb:67:in `each'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `instance_exec'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `run'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/initializable.rb:59:in `block in run_initializers'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
09:30:40 rails.1   | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/initializable.rb:58:in `run_initializers'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/application.rb:353:in `initialize!'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/railtie.rb:185:in `public_send'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/railtie.rb:185:in `method_missing'
09:30:40 rails.1   | 	from /home/thomas/Farmbot-Web-App/config/environment.rb:4:in `<top (required)>'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
09:30:40 rails.1   | 	from config.ru:3:in `block in <main>'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
09:30:40 rails.1   | 	from config.ru:in `new'
09:30:40 rails.1   | 	from config.ru:in `<main>'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:24:in `app'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:42:in `start'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:135:in `block in perform'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `tap'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/server/server_command.rb:130:in `perform'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
09:30:40 rails.1   | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
09:30:40 rails.1   | 	from bin/rails:4:in `require'
09:30:40 rails.1   | 	from bin/rails:4:in `<main>'
09:30:40 logger.1  | /home/thomas/Farmbot-Web-App/app/lib/key_gen.rb:15:in `initialize': No such file or directory @ rb_sysopen - /keys/production.pem (Errno::ENOENT)
09:30:40 logger.1  | 	from /home/thomas/Farmbot-Web-App/app/lib/key_gen.rb:15:in `open'
09:30:40 logger.1  | 	from /home/thomas/Farmbot-Web-App/app/lib/key_gen.rb:15:in `generate_new_key'
09:30:40 logger.1  | 	from /home/thomas/Farmbot-Web-App/app/lib/key_gen.rb:28:in `current'
09:30:40 logger.1  | 	from /home/thomas/Farmbot-Web-App/app/controllers/api/public_keys_controller.rb:6:in `<class:PublicKeysController>'
09:30:40 logger.1  | 	from /home/thomas/Farmbot-Web-App/app/controllers/api/public_keys_controller.rb:4:in `<module:Api>'
09:30:40 logger.1  | 	from /home/thomas/Farmbot-Web-App/app/controllers/api/public_keys_controller.rb:3:in `<top (required)>'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:379:in `block in require_or_load'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:36:in `block in load_interlock'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies/interlock.rb:11:in `loading'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:36:in `load_interlock'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:357:in `require_or_load'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:335:in `depend_on'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:251:in `require_dependency'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:475:in `each'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:475:in `block in eager_load!'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:473:in `each'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:473:in `eager_load!'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/engine.rb:354:in `eager_load!'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/application/finisher.rb:67:in `each'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/application/finisher.rb:67:in `block in <module:Finisher>'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `instance_exec'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `run'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/initializable.rb:59:in `block in run_initializers'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
09:30:40 logger.1  | 	from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/initializable.rb:58:in `run_initializers'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/application.rb:353:in `initialize!'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/railtie.rb:185:in `public_send'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/railtie.rb:185:in `method_missing'
09:30:40 logger.1  | 	from /home/thomas/Farmbot-Web-App/config/environment.rb:4:in `<top (required)>'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/application.rb:329:in `require_environment!'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/command/actions.rb:16:in `require_application_and_environment!'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/runner/runner_command.rb:27:in `perform'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
09:30:40 logger.1  | 	from /home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
09:30:40 logger.1  | 	from bin/rails:4:in `require'
09:30:40 logger.1  | 	from bin/rails:4:in `<main>'
09:30:40 rails.1   | exited with code 1
09:30:40 system    | sending SIGTERM to all processes
09:30:40 logger.1  | exited with code 1
09:30:40 worker.1  | [Worker(host:toto-pc pid:4942)] Exiting...
09:30:40 worker.1  | 2018-04-06T09:30:40+0200: [Worker(host:toto-pc pid:4942)] Exiting...
09:30:40 webpack.1 | terminated by SIGTERM
09:30:45 worker.1  | exited with code 0
09:30:45 system    | sending SIGKILL to all processes
rails aborted!
Command failed with status (1): [PORT=3000 bundle exec foreman start --proc...]
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/file_utils.rb:57:in `sh'
/home/thomas/Farmbot-Web-App/lib/tasks/api.rake:12:in `block (2 levels) in <top (required)>'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/command.rb:46:in `invoke'
/home/thomas/.rvm/gems/ruby-2.5.0@farmbot-web-app/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => api:start
"
Tell me if you want more informations. 

Thanks,
Thomas

**Comment by RickCarlino** [comment]
@ThomasLegris Please try running `rake keys:generate` and then running `rails api:start`.

**Comment by RickCarlino** [comment]
@ThomasLegris I'm glad to hear you got it working! :tada:

In the future, please start new issues when you have a question that is not related to the original content of the issue thread.

To answer your question: The Web App was not intended to be used as a content management system (such as Wordpress) so there is currently no easy way to accomplish this. To add a new tab to the app, you would need to modify the source code of the app to have such a page.

If you are familiar with React developement, the following files would be a good starting point:

 * `webpack/route_config.ts`
 * `webpack/nav/nav_links.tsx`

If you have any further questions about modifying the application source code, please [create a new issue](https://github.com/FarmBot/Farmbot-Web-App/issues/new?title=How%20do%20I%20add%20new%20pages?).
