### ISSUE TITLE
Web-app modifications

### ISSUE THREAD

**Issue by ThomasLegris** [FarmBot/Farmbot-Web-App#807]
# Expected Behavior
We want to modify the web-app. We are adding a new Page named "NouvelOnglet"
Modification of next files :oncoming_police_car: 
- nav_links
- route_config
- add a folder named "NouvelOnglet" in Webpack with only one file : "index.tsx"

# Actual Behavior
There are several problems about the code that I have written. I have pasted all problems and all codes that I had modified. 
# Steps to Reproduce

# My FarmBot API Version

Run `git log -1` and paste the results here
#806 

Here is screenshots 
![route_configpb](https://user-images.githubusercontent.com/34026747/39179999-0dd36856-47b6-11e8-998a-0b27d8b3c91e.png)
![nav_linkspb](https://user-images.githubusercontent.com/34026747/39180000-0df40822-47b6-11e8-8f90-f8094156ad85.png)
![pagenotfound](https://user-images.githubusercontent.com/34026747/39180002-0e223814-47b6-11e8-8f1a-15862f493fab.png)
![error](https://user-images.githubusercontent.com/34026747/39180003-0e4706da-47b6-11e8-91e1-e84816ff2ebd.png)

I don't understand "map_to_state" and why my NouvelOnglet render() couldn't work.

Thank you in advance,

**Comment by RickCarlino** [comment]
@ThomasLegris 

 > `Page Not Found`

You need to put your `page("Nouvel...")` above the catch-all route (`page(*)`). Probably what is happening is that the catch-all route is taking higher precedence than your custom page.

 >  xyz is not a module

Your `import` path for `./state_to_props` is not correct. There is no `state_to_props.ts` file in the current file's directory.

 > I don't understand "map_to_state"

This is a part of Redux state management. Unfortunately, I don't have time to provide training on React and Redux, but I can point you to some good tutorials:

 * [React Basic Intro](https://egghead.io/courses/the-beginner-s-guide-to-react)
 * [Redux intro](https://egghead.io/courses/getting-started-with-redux)
 * [Building React Apps with Typescript](https://egghead.io/courses/use-typescript-to-develop-react-applications)

The resources above are the extent of support that I am able to provide. An understanding of these tools is a pre-requiste to customization of the web app. Additionally, I would **highly recomend [StackOverflow](https://stackoverflow.com/search?q=redux)**, as your questions are more related to React, Typescript and Redux than to Farmbot itself. StackOverflow has a much larger community that can help you start out and, generally speaking, they have a fast turn around time as long as your follow their [guidelines](https://stackoverflow.com/help/how-to-ask).
