### ISSUE TITLE
Selfhost installation fails...

### ISSUE THREAD

**Issue by muenchris** [FarmBot/Farmbot-Web-App#868]
# Expected Behavior
Should run after the instructions given
# Actual Behavior
rails api:start 
Fails - looks like IP of API_HOST given in application.yml was not taken...
| => Rails 5.1.6 application starting in production on http://0.0.0.0:3000
shortly after "unable to start"
The entry API_HOST: is set correctly in the application.yml but it looks like the environment variables are not set at all

# Steps to Reproduce
I installed a fresh new Ubuntu 18.04 (Latest Ubuntu) on a VM with 4 Cores, 4GB Ram and 32GB HD
Followed all steps in the "ubuntu_example.sh" but...
---There is an issue in that document:
LIne 57 and line 58 dont make sense in that order
57 opens the PostGres command prompt and 58 is a bash command that will not execute in PostGres.
Is 58 required BEFORE 57 or AFTER 61?

Also line 76 and 77 say open new Tab and enter command there
But with a new tab the terminal does not run RAIL anymore:

> chris@ubuFarmbot:~/Farmbot-Web-App$ rails mqtt:start
> Command 'rails' not found, but can be installed with:
> sudo apt install ruby-railties

It does work fine (rails mqtt:start) in the first tab where all the other setup calls went (but rails api:start with the error above). It does fail too with 

> {"init terminating in do_boot",{could_not_start,rabbit_auth_backend_jwt,{{shutdown,{failed_to_start_child,rabbit_auth_backend_jwt_pub_key_fetcher,{error,{failed_connect,[{to_address,{"192.168.3.216",3000}},{inet,[inet],econnrefused}]}}}},{rabbit_auth_backend_jwt_app,start,[normal,[]]}}}}
> init terminating in do_boot ()

# My FarmBot API Version
whatever is current on your Github

Run `git log -1` and paste the results here

**Comment by RickCarlino** [comment]
@muenchris 

 > 57 opens the PostGres command prompt and 58 is a bash command that will not execute in PostGres.

Yes, this is a typo. Thanks for bringing it to our attention. I will update the file shortly.

 > Command 'rails' not found

Did you log in / out after installing RVM? One workaround might be to run `rvm use 2.5.1` every time you open a new tab.

Please let me know if that doesn't work and I can investigate further.

**Comment by muenchris** [comment]
If I logout-login (of Ubuntu) “rails” is not even found in the main terminal.

If I “rvm use 2.5.1” and then “rails api:start” I still get the not that “Command ‘rails’ not found, but can be installed with ‘sudo apt install ruby-railities’”. I have not done this (as its not in your ubuntu_example.sh) – should I do this?

I tried to manuall set the Environment variable “API_HOST=<myIP>” but that did not help either

On your main page under “Config Settings (important)” it says “Your server wont run without setting ENV variables first”.
But all the variables in my application.yml are not visible in the ENV. Is the file not loaded correctly?
The MQTT starter seems to read it just fine as the MQTT Host is found correctly and the RMQ is trying to connect to the API_HOST (same Ubuntu VM).

My Application.yml has only these entries:
API_HOST: "192.168.3.216"  <- this is the IP of my UbuntuVM and I can reach this from the Farmbot and other PCs
API_PORT: "3000"
DEVISE_SECRET: "485282..some Key I greated with rake secret”
OS_UPDATE_SERVER: https://api.github.com/repos/farmbot/farmbot_os/releases/latest
MQTT_HOST: "192.168.3.216"
SMTP_HOST: "..my email server.."
SMTP_PORT: "..my email port.."
NO_EMAILS: "TRUE"
MQTT_VHOST: "/"
RUN_CAPYBARA: "false"
RAILS_ENV: "production"

Right now both “Rails” do not start…MQTT looks better but requires that the api is running, correct?

Thanks for your help

Cheers
Chris

**Comment by RickCarlino** [comment]
@muenchris 

 > I have not done this (as its not in your ubuntu_example.sh) – should I do this?

Correct, this should be handled by RVM. Installing Ruby components via `apt-get` can sometimes cause problems.

 > MQTT looks better but requires that the api is running, correct?

Correct, you will need to load the API before the MQTT process.

Let's try this:

0. `cd wherever_the_app_is_installed`
1. `rvm use 2.5.1` (again)
2. `gem install bundler`
3. `bundle install`
4. `rvm list`
5. (if nothing went wrong in the steps above) `rails api:start`

Please paste your error logs and the results of `rvm list`. It is possible that RVM is installed fine but the Rails deps did not install correctly for whatever reason.

**Comment by muenchris** [comment]
I don’t see anything wrong after executing the lines below…except:
[cid:image001.png@01D3F74C.21D1A940]

After I “rails api:start” it still fails
[cid:image002.png@01D3F74C.21D1A940]

Then lots of log output…in the end:

[cid:image003.png@01D3F74C.5BED7460]

Chris

**Comment by RickCarlino** [comment]
@muenchris It seems like your email client is not sending image attachments correctly. Can you please post the screenshots using the [Github link](https://github.com/FarmBot/Farmbot-Web-App/issues/868).
