### ISSUE TITLE
Sync called from farmware is unstable

### ISSUE THREAD

**Issue by etcipnja** [FarmBot/Farmbot-Web-App#875]
# Expected Behavior
When I call 
```
node = {'kind': 'sync', 'args': {}}
        response = requests.post(farmware_url + 'api/v1/celery_script', data=json.dumps(node), headers=headers)
```
I expect it to sync with the bot or error generated.

# Actual Behavior
Error is not generated but it is not syncing sometimes 

# Steps to Reproduce
```
import requests
import json
import os
import datetime

try:
    headers = {'Authorization': 'Bearer ' + os.environ['API_TOKEN'],
               'content-type': 'application/json'}

    #get all sequences
    print('Loading all sequences ...')
    response = requests.get('https://my.farmbot.io/api/sequences', headers=headers)
    response.raise_for_status()
    all_sequences=response.json()

    #find sequence that flashes the light
    print('Finding sequence [FLASH LIGHT] ...')
    sequence=next(i for i in all_sequences if i['name'].lower() == "flash light")

    for i in range(1,10):
        s = 1 if i % 2 == 0 else 10
        print('-----------{}-----------'.format(s))

        #update wait duration
        wait = next(x for x in sequence['body'] if x['kind'] == 'wait')
        wait['args']['milliseconds'] = s*1000

        #save
        response = requests.put("https://my.farmbot.io/api/sequences/{}".format(sequence['id']), headers=headers, data=json.dumps(sequence))
        response.raise_for_status()

        #sync
        print('Syncing ...')
        node = {'kind': 'sync', 'args': {}}
        response = requests.post(os.environ['FARMWARE_URL'] + 'api/v1/celery_script', data=json.dumps(node), headers=headers)
        response.raise_for_status()

        #executing
        print('Excecuting ...')
        start = datetime.datetime.utcnow()
        node = {'kind': 'execute', 'args': {'sequence_id': sequence['id']}}
        response = requests.post(os.environ['FARMWARE_URL'] + 'api/v1/celery_script', data=json.dumps(node), headers=headers)
        response.raise_for_status()
        duration=datetime.datetime.utcnow() - start
        if abs(s-duration.seconds)>5: print ('FAILED, expected {}s, actual {}s'.format(s,duration.seconds))
        else: print ('PASSED, expected {}s, actual {}s'.format(s,duration.seconds))

    print('Done.')

except requests.exceptions.HTTPError as error:
    print('HTTP error {} {} '.format(error.response.status_code,error.response.text[0:100]))
except Exception as e:
    print('Something went wrong: {}'.format(str(e)))
```
# Log

```
Loading all sequences ...
Finding sequence [FLASH LIGHT] ...
-----------10-----------
Syncing ...
Excecuting ...
PASSED, expected 10s, actual 10s
-----------1-----------
Syncing ...
Excecuting ...
FAILED, expected 1s, actual 10s
-----------10-----------
Syncing ...
Excecuting ...
PASSED, expected 10s, actual 10s
-----------1-----------
Syncing ...
Excecuting ...
FAILED, expected 1s, actual 10s
-----------10-----------
Syncing ...
Excecuting ...
FAILED, expected 10s, actual 1s
-----------1-----------
Syncing ...
Excecuting ...
FAILED, expected 1s, actual 10s
-----------10-----------
Syncing ...
Excecuting ...
FAILED, expected 10s, actual 1s
-----------1-----------
Syncing ...
Excecuting ...
PASSED, expected 1s, actual 1s
-----------10-----------
Syncing ...
Excecuting ...
FAILED, expected 10s, actual 1s
Done.
```

**Comment by gabrielburnworth** [comment]
First off, thank you for including the script used to reproduce the issue!

The results experienced here have more to do with how syncing works than with something not working. Put very briefly, before FarmBot OS can sync it must have received a broadcast message from the API indicating that a change to a resource has been made.

The issue here is the time it takes for a change made to a resource in the API to be broadcast to FarmBot OS. It is syncing every time you tell FarmBot OS to sync, but since the sync command is sent very quickly after the change is made, FarmBot OS has not yet received the change from the API.

You can get an idea of how long it takes for the API to broadcast a change by watching the sync button in the Web App after saving a resource. The button will turn gray while waiting for the API to broadcast the change to FarmBot OS, and regain its color once it has done so, indicating that a sync of the resource will include the latest update made to it.

A simple workaround for your situation might be to add a `time.sleep(10)` between saving the sequence and syncing.

**Comment by etcipnja** [comment]
well, I certainly can cope with this. However this doesn't look like a sound design decision. 
It is not clear why FarmBot OS has to wait for the signal? What difference this signal makes? 

If user posted a change and change was accepted and then user sent sync command and sync was accepted - the data must be consistent, there could be no any race condition here. User shall not worry about your internal mechanism and delays that he can not predict or be aware of.

Aslo: I did not submit it here because I was not able to reproduce it reliably, but whaat I also saw is even more strange
- Farmware sends sync command 
- button on the web app goes to 'syncing' -> 'synced' -> 'syncing' -> synced' ->.... -> 'sync failed'

This 'sync failed' status is not conveyed to the farmware - so it continue its execution. In my case it meant that the watering duration was not updated and a single Carrot got 8 liters of water!
read more here https://github.com/etcipnja/MLH

**Comment by ConnorRigby** [comment]
Sync status is available to Farmware's in the bots state endpoint. `/api/v1/bot/state` will have a rather large blob of data you can look thru. If you look at `informational_settings.sync_status` you will see its current status. 

Farmbot OS has to wait for the signal to keep consistency between the OS, Frontend, and Backend. The API is the single source of truth, so it _must_ dispatch its version of the truth to everyone else, and everyone else must agree. So in your case you are changing the API's version of the truth, then it is sending that out to anyone listening including Farmbot OS. If this is something you'd like to handle in your Farmware you can do something along the lines of polling the `bot/state` endpoint. 

```python
while(get_bot_state().informational_settings.sync_status != "syncing"):
   time.sleep(100)

do_sync()
while(get_bot_state().informational_settings.sync_status == "syncing"):
   time.sleep(100)

print("sync results: {}", get_bot_state().informational_settings.sync_status)

```
