### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by patricknoack** [FarmBot/Farmbot-Web-App#880]
# Expected Behavior
Installation wirks

# Actual Behavior
Installation fails, s. logiles

# Steps to Reproduce
Install FarmBot Webserver on Ubuntu 18.04.
# Results of `git log -1`
[farmbot_logs.zip](https://github.com/FarmBot/Farmbot-Web-App/files/2083330/farmbot_logs.zip)
[farmbot_logs.zip](https://github.com/FarmBot/Farmbot-Web-App/files/2083335/farmbot_logs.zip)

Run `git log -1` and paste the results here.

**Comment by RickCarlino** [comment]
@patricknoack 

A few things:

1. It appears that you ran the commands outside of the installation directory. For commands like `npm run test` or `rails api:start` to work, you need to [use the "cd" command to enter the installation directory](http://www.informit.com/blogs/blog.aspx?uk=The-10-Most-Important-Linux-Commands) where `Farmbot-Web-App` resides. Most likely `cd ~/Farmbot-Web-App`.
2. You did not delete unused configuration variables. The application will not run correctly with extra / unused config vars. Try pasting this into `application.yml` instead:

```
API_HOST:         "98.76.54.32"                                                         
API_PORT:         "3000"                                                                
MQTT_HOST:        "98.76.54.32"                                                        
NO_EMAILS:        "TRUE"                                                               
OS_UPDATE_SERVER: "https://api.github.com/repos/farmbot/farmbot_os/releases/late
SECRET_KEY_BASE:  "RUN `rake secret` AND PASTE THE RESULTS HERE"
```
