### ISSUE TITLE
 No Buttons on local Server 

### ISSUE THREAD

**Issue by derletztename** [FarmBot/Farmbot-Web-App#883]
Hi Guys,

I got my local Server running and ready for the field. It has an internet connection and I can login.
But for some reasons - I don’t understand - there are none of those buttons that should be on the web-app.
So no add plants button, none of the calibration buttons/field, none on the farmware page and none in the settings.
How can I get this buttons there? I am using edge as a browser which works fine when I am using the official farmbot server.
I just saw, it also says invalid date on my local server. Maybe this is connected to the missing buttons issue?
Also Version says “none” which should be different I guess

First posted in the forum, but I guess it should be here. Nevertheless, I'll crosslink the threads for others to find the solution faster:
https://forum.farmbot.org/t/no-buttons-on-local-server/3669/2

**Comment by RickCarlino** [comment]
@derletztename 

 >  there are none of those buttons that should be on the web-app

 * What version of FBOS is your device running?
 * Is the device online?
 * Do you see any errors in the javascript console? (ctrl + shift + j)

 > I am using edge as a browser

We don't test against Edge. It's always best to try against Chrome (preferred) or Firefox (seems to work OK).

 > says invalid date on my local server

You are completely off grid, correct? We are aware of a bug in off-grid systems due to an inability to contact an NTP server. We are working on a fix for a future version of FBOS.

 > Version says “none”

This should not create an issues. The version is just there for convinience.

**Comment by derletztename** [comment]
Thanks for answering fast RickCarlino,
I have no idea what FBOS is and how I find out which version I am using. I use Ubuntu Server 18.04 with just the things added your manual wanted me to do.
Googling hadn't helped how to find out what FBOS I am using. Could you maybe tell me how to find out?

The device is still on my desk, till it runs smoothly ( I have to rebuild the plants via the web app as I am not able to perform the coding wizardry you told me to do ;)
then it will move to the field, but still keep an internet connection via a mobile LTE hotspot.

My personal experience was that firefox did not work very good. I had issues drag and dropping plants with firefox, but none with edge.

**Comment by RickCarlino** [comment]
@derletztename FBOS = "FarmBot OS". Pardon my acronym usage. `6.4.3` is the latest version.

Do you know which version you are running? Have you had any indication that the device was able to connect yet?

**Comment by derletztename** [comment]
I googled for quite some time to understand what FBOS might be :D
I have not yet connected the local server to the farmbot. Farmbot is still connected to your public server, so I can use it for watering and stuff. I don't wanted to make the move before the server is running properly.
I think, I should be able to drag and drop the plants onto the field without the farmbot is connected. Also the buttons should be visible, shouldn't they?

**Comment by RickCarlino** [comment]
@derletztename It sounds like a browser rendering issue then. Please install Chrome and try again (it would help if we could see a screenshot).

**Comment by derletztename** [comment]
Yeah, this is crazy. So when I use your server, edge is working perfectly fine. But on my local server with edge there are not button, but with chrome they are there...
I am using chrome for farmbot work from now on... just to be sure ;)

**Comment by derletztename** [comment]
Thanks for the support

**Comment by RickCarlino** [comment]
Glad you got it worked out, @derletztename !

Chrome is, unfortunately, our only supported browser at the moment so it is best to avoid Edge where possible.
