### ISSUE TITLE
Sequences with wait(60000) can't be executed from the API

### ISSUE THREAD

**Issue by etcipnja** [FarmBot/Farmbot-Web-App#955]
# Expected Behavior
Sequence with wait(60000) command (or longer) can be executed from the API

# Actual Behavior
```
node = {'kind': 'execute', 'args': {'sequence_id': sequence['id']}}
response = requests.post(self.farmware_url + 'api/v1/celery_script', data=json.dumps(node),
                        headers=self.headers)
```
second line generates exception 
```
('Connection aborted.', BadStatusLine("''",))
```
# Steps to Reproduce
- create a sequence open watering, wait 60+ sec, stop watering
- run the script above - you get exception
- change the wait duration to 59s, run script - no exception  

note: any sequence can be executed from the web page without any problems. 

Version 6.4.8

**Comment by gabrielburnworth** [comment]
Just to clarify, you mean from a Farmware using the FarmBot OS Farmware API, right? [FarmBot/farmbot_os](https://github.com/FarmBot/farmbot_os/issues) might be the more relevant place for this issue.

**Comment by etcipnja** [comment]
thank you, resubmitted there
