### ISSUE TITLE
Running Web-pack and mqtt-gateway in background without ssh connected to it

### ISSUE THREAD

**Issue by samghotra** [FarmBot/Farmbot-Web-App#977]
# Expected Behavior
To have the web-app running after the ssh session has been closed.

# Actual Behavior
After the ssh session to the linux server is closed, the web app crashes with this error

*Webpack::Rails::Manifest::ManifestLoadError in Dashboard#front_page*

 \</head>
 \<body>
    <%= javascript_include_tag *webpack_asset_paths("front_page") %>
    \<%# Foo %>
 \</body>

Rails.root: /home/farmbot/Farmbot-Web-App

Application Trace | Framework Trace | Full Trace
app/views/dashboard/front_page.html.erb:7:in `_app_views_dashboard_front_page_html_erb___1636015566348202574_66386900'
app/controllers/dashboard_controller.rb:23:in `block (2 levels) in <class:DashboardController>'
Request

# Steps to Reproduce
I tried to install docker and run a docker container, but I realised it is already running docker containers. I am not sure how to keep it going.
# Results of `git log -1`

farmbot@FARMBOT:~/Farmbot-Web-App$ git log -1
commit efe830640ed23bb7cff8557e5b3c98cf07d5ff9a
Merge: ea7f34c a8204fb
Author: Rick Carlino <RickCarlino@users.noreply.github.com>
Date:   Sat Mar 10 18:44:06 2018 -0600

    Merge pull request #713 from RickCarlino/firmware_config_default

    Change default of encoder_scaling_*

**Comment by RickCarlino** [comment]
SSH will close applications after you log out if you don't use a tool like `nohup`, `screen` or `tmux` or convert it to a service.

[This question on AskUbuntu](https://askubuntu.com/questions/8653/how-to-keep-processes-running-after-ending-ssh-session/222855#222855) offers numerous solutions.
